import React, { createContext, useContext, useState } from 'react';

export const translations = {
  pt: {
    name: 'Português',
    flag: '🇵🇹',
    // Onboarding
    continue: 'Continuar',
    whereAreYou: 'Onde estás? 📍',
    locationSubtitle: 'Vamos mostrar-te planos e pessoas perto de ti.',
    useMyLocation: 'Usar a minha localização',
    detecting: 'A detetar...',
    tapToDetect: 'Toca para detetar automaticamente',
    locationSetTo: 'Localização definida para',
    chooseLanguage: 'Escolhe o teu idioma 🌍',
    languageSubtitle: 'Seleciona o idioma em que queres usar a aplicação.',
    whatsYourName: 'Qual é o teu nome? 👋',
    nameSubtitle: 'É assim que outros utilizadores te vão ver na Vybt.',
    yourNamePlaceholder: 'O teu nome...',
    whatsYourGender: 'Qual é o teu género?',
    genderSubtitle: 'Ajuda-nos a personalizar a tua experiência',
    female: 'Feminino',
    male: 'Masculino',
    other: 'Outro',
    whatsYourBirthday: 'Qual é a tua data de nascimento?',
    birthdaySubtitle: 'Tens de ter 16+ anos para usar a Vybt',
    ageVerified: '✓ Idade verificada',
    yearsOld: 'anos',
    mustBe16: 'Tens de ter pelo menos 16 anos para usar a Vybt',
    addYourPhotos: 'Adiciona as tuas fotos',
    photosSubtitle: 'É necessária pelo menos 1 foto (primeira foto para verificação)',
    mainPhoto: 'Principal (Obrigatória)',
    photo: 'Foto',
    photoVerificationWarning: 'A tua primeira foto será usada para verificação do perfil. Certifica-te de que mostra claramente o teu rosto.',
    whatsYourVibe: 'Qual é o teu vibe?',
    vibeSubtitle: 'Seleciona {min}–{max} estilos musicais que adoras',
    searchVibes: 'Pesquisar vibes...',
    vibesCount: 'vibes',
    selected: 'selecionado',
    limitReached: 'Limite atingido — remove um para escolher outro',
    whatPartiesDoYouLove: 'Que festas adoras?',
    partySubtitle: 'Seleciona {min}–{max} tipos de festas',
    searchPartyTypes: 'Pesquisar tipos de festas...',
    typesCount: 'tipos',
    // Welcome complete
    welcomeTitle: 'Bem-vindo!',
    accountReady: 'A tua conta está pronta',
    searchPlansTonight: 'Pesquisar planos para esta noite?',
    explorePlansLocation: 'Explorar todos os planos na tua localização',
    letsGo: "Vamos lá! 🎉",
    // Verification step
    verifyYourProfile: 'Verifica o teu perfil',
    verifyDesc1: 'Tire uma selfie para conseguir o ',
    verifyBadge: 'selo azul de verificação',
    verifyDesc2: ' e construir confiança com outros usuários.',
    verifyNow: 'Verificar Agora',
    skipForNow: 'Saltar por agora',
    // Navigation
    home: 'Início',
    explore: 'Explorar',
    create: 'Criar',
    messages: 'Mensagens',
    profile: 'Perfil',
    // BottomNav menu
    addStory: 'Adicionar Story',
    createNewPlan: 'Criar novo Plano',
    // Home
    myPlans: 'Meus Planos',
    seeAll: 'Ver tudo',
    tonight: 'Esta Noite',
    forYou: 'Para Ti',
    happeningNow: 'A Acontecer Agora',
    // Profile
    myFriends: 'Os Meus Amigos',
    joinedPartyPlans: 'Planos que Participei',
    myExperienceStories: 'As Minhas Histórias',
    profileVerified: 'Perfil Verificado ✓',
    verifyProfile: 'Verificar o Meu Perfil',
    verifyBadge: 'Obtém um crachá azul para ganhar confiança',
    friends: 'Amigos',
    parties: 'Festas',
    stories: 'Histórias',
    ambassadorProgram: 'Programa Ambassador',
    allPerksUnlocked: 'Todos os benefícios desbloqueados!',
    friendsInvited: 'amigos convidados',
    // Edit Profile
    editProfile: 'Editar Perfil',
    photos: 'Fotos (máx. 3)',
    displayName: 'Nome de Exibição',
    bio: 'Bio',
    bioPlaceholder: 'Conta algo sobre ti...',
    dateOfBirth: 'Data de Nascimento',
    age: 'Idade',
    yourLocation: 'A Tua Localização',
    detectingLocation: 'A detetar a tua localização...',
    tapToUseLocation: 'Toca para usar a localização atual',
    searchRadius: 'Raio de Pesquisa',
    yourVibes: 'Os Teus Vibes (máx. 5)',
    preferredPartyTypes: 'Tipos de Festas Preferidas',
    saveChanges: 'Guardar Alterações',
    main: 'Principal',
    // Settings
    settings: 'Definições',
    account: 'Conta',
    notifications: 'Notificações',
    manageAlerts: 'Gerir os teus alertas',
    language: 'Idioma',
    legalCommunity: 'Legal & Comunidade',
    communityGuidelines: 'Diretrizes da Comunidade',
    termsConditions: 'Termos e Condições',
    privacyPolicy: 'Política de Privacidade',
    support: 'Suporte',
    helpFaq: 'Ajuda & FAQ',
    session: 'Sessão',
    logOut: 'Terminar Sessão',
    deleteAccount: 'Eliminar Conta',
    deleteAccountSub: 'Remover permanentemente os teus dados',
    chooseLanguageTitle: 'Escolher Idioma',
    administration: 'Administração',
    moderationPanel: 'Painel de Moderação',
    moderationSub: 'Rever denúncias de conteúdo',
    // Explore
    plans: 'Planos',
    people: 'Pessoas',
    map: 'Mapa',
    searchPlans: 'Pesquisar planos...',
    searchPeople: 'Pesquisar pessoas...',
    filters: 'Filtros',
    allTag: 'Todos',
    onFire: 'Em Destaque',
    mostMembers: 'Mais Membros',
    matchesVibes: 'Combina com os Meus Vibes',
    noPlansFound: 'Nenhum plano encontrado',
    noUsersFound: 'Nenhum utilizador encontrado',
    vibesMatch: 'vibes em comum',
    // Profile
    myVibes: 'Os Meus Vibes',
    preferredParties: 'Planos preferidos',
    // Friends
    friendsTab: 'Amigos',
    requests: 'Pedidos',
    noFriendsYet: 'Sem amigos ainda',
    noPendingRequests: 'Sem pedidos pendentes',
    wantsToBeYourFriend: 'Quer ser teu amigo',
    noLocation: 'Sem localização',
    // Notifications
    notifications_title: 'Notificações',
    unread: 'não lidas',
    markAllRead: 'Marcar todas',
    noNotifications: 'Sem notificações',
    removed: 'Removido',
    confirm: 'Confirmar',
    delete: 'Deletar',
    friendRequest: ' te enviou um pedido de amizade.',
    // MyStories
    myExperienceStoriesTitle: 'As Minhas Histórias de Experiência',
    noStoriesYet: 'Ainda não partilhaste nenhuma história',
    addFirstStory: 'Adiciona a Tua Primeira História',
    unknownPlan: 'Plano Desconhecido',
    // Plan Details
    going: 'A ir',
    groupChat: 'Chat do Grupo',
    joinPlan: 'Entrar no Plano',
    leavePlan: 'Sair',
    about: 'Sobre',
    experienceStories: 'Histórias de Experiência',
    shareYourExperience: 'Partilha a tua experiência',
    storiesUnavailableVoting: 'Histórias indisponíveis durante a votação',
    planLimitWarning: 'Atingiste o limite de 3 planos em',
    leaveToJoin: 'Sai de um plano para entrar neste.',
    votingActiveNotice: '🗳️ Período de votação ativo — Não podes entrar ou sair durante a votação (6 horas)',
    planTerminated: '❌ Plano Terminado',
    planTerminatedDesc: 'Este plano foi terminado pelo administrador e será eliminado em 24 horas',
    highlightPlan: 'Destacar este plano - €2.99',
    // Create Plan
    createNewPlanTitle: 'Criar Novo Plano',
    // Add Story
    addStoryTitle: 'Adicionar Story',
    whichPlanIsThisFor: 'Para que plano é esta story?',
    noActivePlans: 'Sem planos ativos ainda.\nEntra num plano e espera que comece.',
    shareStory: 'Partilhar Story',
    processingChecking: 'A processar e verificar conteúdo...',
    // Story visibility
    friendsVisibility: 'Amigos',
    groupOnly: 'Grupo',
    highlight: 'Destaque',
    // Welcome page
    welcomeHero: 'Ei, amigo!',
    welcomeSubtitle: 'Junta-te a nós: vamos conectar e criar os melhores planos\nna tua zona!!!',
    downloadNow: 'Descarregar Agora!',
    allRightsReserved: 'Todos os direitos reservados.',
    // Group Chat
    votingOpen: 'Votação aberta! Toca para votar',
    awaitingAdminDecision: '⏳ A aguardar que o administrador renove ou encerre o plano',
    renewPlan: 'Renovar',
    terminatePlan: 'Encerrar',
    beFirstToMessage: 'Sê o primeiro a enviar uma mensagem!',
    chatLocked: 'Chat bloqueado — aguardando decisão do administrador',
    messagePlaceholder: 'Mensagem...',
    // Admin actions
    adminActions: 'Ações Admin',
    editPlan: 'Editar Plano',
    editPlanUnavailableVoting: 'Indisponível durante a votação',
    editPlanUnavailableEnded: 'Indisponível enquanto o plano está encerrado',
    // Voting modal
    howWasPlan: 'Como foi o plano?',
    yourOpinionHelps: 'A tua opinião ajuda a melhorar eventos futuros',
    votingClosesIn: 'Votação encerra 6 horas após o fim do plano',
    wantToLeavePlan: 'Queres sair deste plano?',
    youVotedBad: 'Votaste que não gostaste do plano',
    yesLeavePlan: 'Sim, sair do plano',
    noStayInGroup: 'Não, permanecer no grupo',
    // Renew plan modal
    adminActionsTitle: 'Ações do Administrador',
    chooseWhatToDo: 'Escolhe o que fazer com este plano',
    renewPlanBtn: '🔄 Renovar Plano',
    terminatePlanBtn: '❌ Terminar Plano',
    cancel: 'Cancelar',
    terminatePlanTitle: 'Terminar Plano ❌',
    terminatePlanDesc: 'O plano será marcado como terminado e ficará visível por 24 horas antes de ser eliminado automaticamente.',
    terminateWarning: '⚠️ Esta ação não pode ser desfeita. Todos os membros verão que o plano foi terminado.',
    back: 'Voltar',
    confirmTermination: 'Confirmar Término',
    renewPlanTitle: 'Renovar Plano 🔄',
    renewPlanDesc: 'Tudo será renovado com nova data e horário. As experience stories anteriores serão mantidas.',
    newDate: 'Nova Data',
    startTime: 'Horário de Início',
    endTime: 'Horário de Término',
    newAddress: 'Novo Endereço',
    fullAddress: 'Endereço completo',
    confirmRenewal: 'Confirmar Renovação',
    // Delete plan modal
    terminatePlanQuestion: 'Encerrar Plano?',
    terminatePlanVisibleDesc: 'O plano será marcado como Encerrado e ficará visível para todos os membros por 24 horas, depois será removido automaticamente.',
    terminated: 'Encerrado',
    terminatePlanConfirm: 'Encerrar Plano',
    // Plan renewed chat message
    planRenewed: '🔄 O plano foi renovado! Let\'s gooo 😎',
    planTerminatedMsg: '❌ O administrador encerrou este plano. O grupo será removido em 24 horas.',
    // Ambassador CTA
    ambassadorCtaTitle: 'Sê o primeiro na tua cidade!',
    ambassadorCtaDesc: 'Não há planos em {city} ainda. Torna-te um Vybt Ambassador e traz o vibe para a tua área!',
    becomeAmbassador: 'Tornar-me Ambassador',
    // Settings - Appearance & Privacy
    appearance: 'Aparência',
    switchToLight: 'Mudar para tema claro',
    switchToDark: 'Mudar para tema escuro',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    privateProfile: 'Perfil Privado',
    publicProfile: 'Perfil Público',
    privateProfileDesc: 'Só amigos vêem os teus stories, planos e amigos',
    publicProfileDesc: 'Toda a gente pode ver o teu perfil completo',
    // GroupChat
    joinPlanToAccess: 'Junta-te ao plano para acederes ao grupo e conversar.',
    backBtn: '← Voltar',
    planUpdated: '✏️ Plano atualizado',
    terminatedBanner: '❌ Terminado',
    happeningNowHeader: 'Seu plano está acontecendo agora!'
  },

  en: {
    name: 'English',
    flag: '🇬🇧',
    // Onboarding
    continue: 'Continue',
    whereAreYou: 'Where are you? 📍',
    locationSubtitle: "We'll show you plans and people nearby.",
    useMyLocation: 'Use my current location',
    detecting: 'Detecting...',
    tapToDetect: 'Tap to detect automatically',
    locationSetTo: 'Location set to',
    chooseLanguage: 'Choose your language 🌍',
    languageSubtitle: 'Select the language you want to use the app in.',
    whatsYourName: "What's your name? 👋",
    nameSubtitle: 'This is how other users will see you on Vybt.',
    yourNamePlaceholder: 'Your name...',
    whatsYourGender: "What's your gender?",
    genderSubtitle: 'This helps us personalize your experience',
    female: 'Female',
    male: 'Male',
    other: 'Other',
    whatsYourBirthday: "What's your birthday?",
    birthdaySubtitle: 'You must be 16+ to use Vybt',
    ageVerified: '✓ Age verified',
    yearsOld: 'years old',
    mustBe16: 'You must be at least 16 years old to use Vybt',
    addYourPhotos: 'Add your photos',
    photosSubtitle: 'At least 1 photo is required (first photo for verification)',
    mainPhoto: 'Main (Required)',
    photo: 'Photo',
    photoVerificationWarning: 'Your first photo will be used for profile verification. Make sure it clearly shows your face.',
    whatsYourVibe: "What's your vibe?",
    vibeSubtitle: 'Select {min}–{max} music styles you love',
    searchVibes: 'Search vibes...',
    vibesCount: 'vibes',
    selected: 'selected',
    limitReached: 'Limit reached — deselect one to pick another',
    whatPartiesDoYouLove: 'What plans do you love?',
    partySubtitle: 'Select {min}–{max} party types',
    searchPartyTypes: 'Search party types...',
    typesCount: 'types',
    // Welcome complete
    welcomeTitle: 'Welcome!',
    accountReady: 'Your account is ready',
    searchPlansTonight: 'Search for plans tonight?',
    explorePlansLocation: 'Explore all plans in your location',
    letsGo: "Let's Go! 🎉",
    // Verification step
    verifyYourProfile: 'Verify your profile',
    verifyDesc1: 'Take a live selfie to get a ',
    verifyBadge: 'blue verified badge',
    verifyDesc2: ' and build trust with other users.',
    verifyNow: 'Verify Now',
    skipForNow: 'Skip for now',
    // Navigation
    home: 'Home',
    explore: 'Explore',
    create: 'Create',
    messages: 'Messages',
    profile: 'Profile',
    // BottomNav menu
    addStory: 'Add Story',
    createNewPlan: 'Create new Plan',
    // Home
    myPlans: 'My Plans',
    seeAll: 'See all',
    tonight: 'Tonight',
    forYou: 'For You',
    happeningNow: 'Happening Now',
    // Profile
    myFriends: 'My Friends',
    joinedPartyPlans: 'Joined Party Plans',
    myExperienceStories: 'My Experience Stories',
    profileVerified: 'Profile Verified ✓',
    verifyProfile: 'Verify Your Profile',
    verifyBadge: 'Get a blue badge to build trust',
    friends: 'Friends',
    parties: 'Parties',
    stories: 'Stories',
    ambassadorProgram: 'Ambassador Program',
    allPerksUnlocked: 'All perks unlocked!',
    friendsInvited: 'friends invited',
    // Edit Profile
    editProfile: 'Edit Profile',
    photos: 'Photos (max 3)',
    displayName: 'Display Name',
    bio: 'Bio',
    bioPlaceholder: 'Tell others about yourself...',
    dateOfBirth: 'Date of Birth',
    age: 'Age',
    yourLocation: 'Your Location',
    detectingLocation: 'Detecting your location...',
    tapToUseLocation: 'Tap to use current location',
    searchRadius: 'Search Radius',
    yourVibes: 'Your Vibes (max 5)',
    preferredPartyTypes: 'Preferred Party Types',
    saveChanges: 'Save Changes',
    main: 'Main',
    // Settings
    settings: 'Settings',
    account: 'Account',
    notifications: 'Notifications',
    manageAlerts: 'Manage your alerts',
    language: 'Language',
    legalCommunity: 'Legal & Community',
    communityGuidelines: 'Community Guidelines',
    termsConditions: 'Terms and Conditions',
    privacyPolicy: 'Privacy Policy',
    support: 'Support',
    helpFaq: 'Help & FAQ',
    session: 'Session',
    logOut: 'Log Out',
    deleteAccount: 'Delete Account',
    deleteAccountSub: 'Permanently remove your data',
    chooseLanguageTitle: 'Choose Language',
    administration: 'Administration',
    moderationPanel: 'Moderation Panel',
    moderationSub: 'Review content reports',
    // Explore
    plans: 'Plans',
    people: 'People',
    map: 'Map',
    searchPlans: 'Search plans...',
    searchPeople: 'Search people...',
    filters: 'Filters',
    allTag: 'All',
    onFire: 'On Fire',
    mostMembers: 'Most Members',
    matchesVibes: 'Matches My Vibes',
    noPlansFound: 'No plans found',
    noUsersFound: 'No users found',
    vibesMatch: 'vibes match',
    // Profile
    myVibes: 'My Vibes',
    preferredParties: 'Preferred Parties',
    // Friends
    friendsTab: 'Friends',
    requests: 'Requests',
    noFriendsYet: 'No friends yet',
    noPendingRequests: 'No pending requests',
    wantsToBeYourFriend: 'Wants to be your friend',
    noLocation: 'No location',
    // Notifications
    notifications_title: 'Notifications',
    unread: 'unread',
    markAllRead: 'Mark all',
    noNotifications: 'No notifications',
    removed: 'Removed',
    confirm: 'Confirm',
    delete: 'Delete',
    friendRequest: ' sent you a friend request.',
    // MyStories
    myExperienceStoriesTitle: 'My Experience Stories',
    noStoriesYet: "You haven't shared any stories yet",
    addFirstStory: 'Add Your First Story',
    unknownPlan: 'Unknown Plan',
    // Plan Details
    going: 'Going',
    groupChat: 'Group Chat',
    joinPlan: 'Join Plan',
    leavePlan: 'Leave',
    about: 'About',
    experienceStories: 'Experience Stories',
    shareYourExperience: 'Share your experience',
    storiesUnavailableVoting: 'Stories unavailable during voting',
    planLimitWarning: "You've reached the limit of 3 plans in",
    leaveToJoin: 'Leave a plan to join this one.',
    votingActiveNotice: '🗳️ Voting period active - Cannot join or leave during voting (6 hours)',
    planTerminated: '❌ Plan Terminated',
    planTerminatedDesc: 'This plan was terminated by the admin and will be deleted in 24 hours',
    highlightPlan: 'Highlight this plan - €2.99',
    // Create Plan
    createNewPlanTitle: 'Create New Plan',
    // Add Story
    addStoryTitle: 'Add Story',
    whichPlanIsThisFor: 'Which plan is this for?',
    noActivePlans: 'No active plans yet.\nJoin a plan and wait for it to start.',
    shareStory: 'Share Story',
    processingChecking: 'Processing & checking content...',
    // Story visibility
    friendsVisibility: 'Friends',
    groupOnly: 'Group',
    highlight: 'Highlight',
    // Welcome page
    welcomeHero: 'Hey, mate!',
    welcomeSubtitle: "Join us: let's connect and create the best plans\nin your area!!!",
    downloadNow: 'Download Now!',
    allRightsReserved: 'All rights reserved.',
    // Group Chat
    votingOpen: 'Voting open! Tap to vote',
    awaitingAdminDecision: '⏳ Waiting for the admin to renew or close the plan',
    renewPlan: 'Renew',
    terminatePlan: 'Close',
    beFirstToMessage: 'Be the first to send a message!',
    chatLocked: 'Chat locked — awaiting admin decision',
    messagePlaceholder: 'Message...',
    // Admin actions
    adminActions: 'Admin Actions',
    editPlan: 'Edit Plan',
    editPlanUnavailableVoting: 'Unavailable during voting',
    editPlanUnavailableEnded: 'Unavailable while the plan is closed',
    // Voting modal
    howWasPlan: 'How was the plan?',
    yourOpinionHelps: 'Your opinion helps improve future events',
    votingClosesIn: 'Voting closes 6 hours after the plan ends',
    wantToLeavePlan: 'Do you want to leave this plan?',
    youVotedBad: 'You voted that you did not enjoy the plan',
    yesLeavePlan: 'Yes, leave the plan',
    noStayInGroup: 'No, stay in the group',
    // Renew plan modal
    adminActionsTitle: 'Admin Actions',
    chooseWhatToDo: 'Choose what to do with this plan',
    renewPlanBtn: '🔄 Renew Plan',
    terminatePlanBtn: '❌ Terminate Plan',
    cancel: 'Cancel',
    terminatePlanTitle: 'Terminate Plan ❌',
    terminatePlanDesc: 'The plan will be marked as terminated and remain visible for 24 hours before being automatically deleted.',
    terminateWarning: '⚠️ This action cannot be undone. All members will see that the plan was terminated.',
    back: 'Back',
    confirmTermination: 'Confirm Termination',
    renewPlanTitle: 'Renew Plan 🔄',
    renewPlanDesc: 'Everything will be renewed with a new date and time. Previous experience stories will be kept.',
    newDate: 'New Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    newAddress: 'New Address',
    fullAddress: 'Full address',
    confirmRenewal: 'Confirm Renewal',
    // Delete plan modal
    terminatePlanQuestion: 'Terminate Plan?',
    terminatePlanVisibleDesc: 'The plan will be marked as Closed and visible to all members for 24 hours, then automatically removed.',
    terminated: 'Closed',
    terminatePlanConfirm: 'Terminate Plan',
    // Plan renewed chat message
    planRenewed: "🔄 The plan has been renewed! Let's gooo 😎",
    planTerminatedMsg: '❌ The admin has closed this plan. The group will be removed in 24 hours.',
    // Ambassador CTA
    ambassadorCtaTitle: 'Be the first in your city!',
    ambassadorCtaDesc: 'There are no plans in {city} yet. Become a Vybt Ambassador and help bring the vibe to your area!',
    becomeAmbassador: 'Become an Ambassador',
    // Settings - Appearance & Privacy
    appearance: 'Appearance',
    switchToLight: 'Switch to light theme',
    switchToDark: 'Switch to dark theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    privateProfile: 'Private Profile',
    publicProfile: 'Public Profile',
    privateProfileDesc: 'Only friends can see your stories, plans and friends',
    publicProfileDesc: 'Everyone can see your full profile',
    // GroupChat
    joinPlanToAccess: 'Join the plan to access the group and chat.',
    backBtn: '← Back',
    planUpdated: '✏️ Plan updated',
    terminatedBanner: '❌ Terminated',
    happeningNowHeader: 'Your plan is happening now!'
  },

  es: {
    name: 'Español',
    flag: '🇪🇸',
    // Onboarding
    continue: 'Continuar',
    whereAreYou: '¿Dónde estás? 📍',
    locationSubtitle: 'Te mostraremos planes y personas cercanas.',
    useMyLocation: 'Usar mi ubicación actual',
    detecting: 'Detectando...',
    tapToDetect: 'Toca para detectar automáticamente',
    locationSetTo: 'Ubicación establecida en',
    chooseLanguage: 'Elige tu idioma 🌍',
    languageSubtitle: 'Selecciona el idioma en el que quieres usar la app.',
    whatsYourName: '¿Cómo te llamas? 👋',
    nameSubtitle: 'Así es como otros usuarios te verán en Vybt.',
    yourNamePlaceholder: 'Tu nombre...',
    whatsYourGender: '¿Cuál es tu género?',
    genderSubtitle: 'Esto nos ayuda a personalizar tu experiencia',
    female: 'Femenino',
    male: 'Masculino',
    other: 'Otro',
    whatsYourBirthday: '¿Cuál es tu cumpleaños?',
    birthdaySubtitle: 'Debes tener 16+ años para usar Vybt',
    ageVerified: '✓ Edad verificada',
    yearsOld: 'años',
    mustBe16: 'Debes tener al menos 16 años para usar Vybt',
    addYourPhotos: 'Añade tus fotos',
    photosSubtitle: 'Se requiere al menos 1 foto (primera foto para verificación)',
    mainPhoto: 'Principal (Obligatoria)',
    photo: 'Foto',
    photoVerificationWarning: 'Tu primera foto se usará para la verificación del perfil. Asegúrate de que muestre claramente tu cara.',
    whatsYourVibe: '¿Cuál es tu vibe?',
    vibeSubtitle: 'Selecciona {min}–{max} estilos musicales que te encantan',
    searchVibes: 'Buscar vibes...',
    vibesCount: 'vibes',
    selected: 'seleccionado',
    limitReached: 'Límite alcanzado — desmarca uno para elegir otro',
    whatPartiesDoYouLove: '¿Qué planes te encantan?',
    partySubtitle: 'Selecciona {min}–{max} tipos de fiestas',
    searchPartyTypes: 'Buscar tipos de fiestas...',
    typesCount: 'tipos',
    // Welcome complete
    welcomeTitle: '¡Bienvenido!',
    accountReady: 'Tu cuenta está lista',
    searchPlansTonight: '¿Buscar planes para esta noche?',
    explorePlansLocation: 'Explorar todos los planes en tu ubicación',
    letsGo: '¡Vamos! 🎉',
    // Verification step
    verifyYourProfile: 'Verifica tu perfil',
    verifyDesc1: 'Tómate una selfie para obtener una ',
    verifyBadge: 'insignia azul de verificación',
    verifyDesc2: ' y generar confianza con otros usuarios.',
    verifyNow: 'Verificar Ahora',
    skipForNow: 'Saltar por ahora',
    // Navigation
    home: 'Inicio',
    explore: 'Explorar',
    create: 'Crear',
    messages: 'Mensajes',
    profile: 'Perfil',
    // BottomNav menu
    addStory: 'Añadir Story',
    createNewPlan: 'Crear nuevo Plan',
    // Home
    myPlans: 'Mis Planes',
    seeAll: 'Ver todo',
    tonight: 'Esta Noche',
    forYou: 'Para Ti',
    happeningNow: 'Pasando Ahora',
    // Profile
    myFriends: 'Mis Amigos',
    joinedPartyPlans: 'Planes a los que me uní',
    myExperienceStories: 'Mis Historias',
    profileVerified: 'Perfil Verificado ✓',
    verifyProfile: 'Verificar mi Perfil',
    verifyBadge: 'Obtén una insignia azul para generar confianza',
    friends: 'Amigos',
    parties: 'Fiestas',
    stories: 'Historias',
    ambassadorProgram: 'Programa Embajador',
    allPerksUnlocked: '¡Todos los beneficios desbloqueados!',
    friendsInvited: 'amigos invitados',
    // Edit Profile
    editProfile: 'Editar Perfil',
    photos: 'Fotos (máx. 3)',
    displayName: 'Nombre de usuario',
    bio: 'Bio',
    bioPlaceholder: 'Cuéntale algo a los demás...',
    dateOfBirth: 'Fecha de Nacimiento',
    age: 'Edad',
    yourLocation: 'Tu Ubicación',
    detectingLocation: 'Detectando tu ubicación...',
    tapToUseLocation: 'Toca para usar la ubicación actual',
    searchRadius: 'Radio de Búsqueda',
    yourVibes: 'Tus Vibes (máx. 5)',
    preferredPartyTypes: 'Tipos de Fiestas Preferidas',
    saveChanges: 'Guardar Cambios',
    main: 'Principal',
    // Settings
    settings: 'Ajustes',
    account: 'Cuenta',
    notifications: 'Notificaciones',
    manageAlerts: 'Gestiona tus alertas',
    language: 'Idioma',
    legalCommunity: 'Legal & Comunidad',
    communityGuidelines: 'Directrices de la Comunidad',
    termsConditions: 'Términos y Condiciones',
    privacyPolicy: 'Política de Privacidad',
    support: 'Soporte',
    helpFaq: 'Ayuda & FAQ',
    session: 'Sesión',
    logOut: 'Cerrar Sesión',
    deleteAccount: 'Eliminar Cuenta',
    deleteAccountSub: 'Eliminar permanentemente tus datos',
    chooseLanguageTitle: 'Elegir Idioma',
    administration: 'Administración',
    moderationPanel: 'Panel de Moderación',
    moderationSub: 'Revisar informes de contenido',
    // Explore
    plans: 'Planes',
    people: 'Personas',
    map: 'Mapa',
    searchPlans: 'Buscar planes...',
    searchPeople: 'Buscar personas...',
    filters: 'Filtros',
    allTag: 'Todos',
    onFire: 'En Llamas',
    mostMembers: 'Más Miembros',
    matchesVibes: 'Coincide con Mis Vibes',
    noPlansFound: 'No se encontraron planes',
    noUsersFound: 'No se encontraron usuarios',
    vibesMatch: 'vibes en común',
    // Profile
    myVibes: 'Mis Vibes',
    preferredParties: 'Fiestas Preferidas',
    // Friends
    friendsTab: 'Amigos',
    requests: 'Solicitudes',
    noFriendsYet: 'Sin amigos aún',
    noPendingRequests: 'Sin solicitudes pendientes',
    wantsToBeYourFriend: 'Quiere ser tu amigo',
    noLocation: 'Sin ubicación',
    // Notifications
    notifications_title: 'Notificaciones',
    unread: 'no leídas',
    markAllRead: 'Marcar todas',
    noNotifications: 'Sin notificaciones',
    removed: 'Eliminado',
    confirm: 'Confirmar',
    delete: 'Borrar',
    friendRequest: ' te mandé una solicitud de amistad.',
    // MyStories
    myExperienceStoriesTitle: 'Mis Historias de Experiencia',
    noStoriesYet: 'Aún no has compartido ninguna historia',
    addFirstStory: 'Añade tu Primera Historia',
    unknownPlan: 'Plan Desconocido',
    // Plan Details
    going: 'Asistiendo',
    groupChat: 'Chat de Grupo',
    joinPlan: 'Unirse al Plan',
    leavePlan: 'Salir',
    about: 'Acerca de',
    experienceStories: 'Historias de Experiencia',
    shareYourExperience: 'Comparte tu experiencia',
    storiesUnavailableVoting: 'Historias no disponibles durante la votación',
    planLimitWarning: 'Has alcanzado el límite de 3 planes en',
    leaveToJoin: 'Sal de un plan para unirte a este.',
    votingActiveNotice: '🗳️ Período de votación activo — No puedes unirte ni salir durante la votación (6 horas)',
    planTerminated: '❌ Plan Terminado',
    planTerminatedDesc: 'Este plan fue terminado por el administrador y se eliminará en 24 horas',
    highlightPlan: 'Destacar este plan - €2.99',
    // Create Plan
    createNewPlanTitle: 'Crear Nuevo Plan',
    // Add Story
    addStoryTitle: 'Añadir Story',
    whichPlanIsThisFor: '¿Para qué plan es esto?',
    noActivePlans: 'Sin planes activos aún.\nÚnete a un plan y espera a que comience.',
    shareStory: 'Compartir Story',
    processingChecking: 'Procesando y verificando contenido...',
    // Story visibility
    friendsVisibility: 'Amigos',
    groupOnly: 'Grupo',
    highlight: 'Destacar',
    // Welcome page
    welcomeHero: '¡Hola, amigo!',
    welcomeSubtitle: 'Únete a nosotros: conectemos y creemos los mejores planes\n¡en tu zona!!!',
    downloadNow: '¡Descargar Ahora!',
    allRightsReserved: 'Todos los derechos reservados.',
    // Group Chat
    votingOpen: '¡Votación abierta! Toca para votar',
    awaitingAdminDecision: '⏳ Esperando que el administrador renueve o cierre el plan',
    renewPlan: 'Renovar',
    terminatePlan: 'Cerrar',
    beFirstToMessage: '¡Sé el primero en enviar un mensaje!',
    chatLocked: 'Chat bloqueado — esperando decisión del administrador',
    messagePlaceholder: 'Mensaje...',
    adminActions: 'Acciones Admin',
    editPlan: 'Editar Plan',
    editPlanUnavailableVoting: 'No disponible durante la votación',
    editPlanUnavailableEnded: 'No disponible mientras el plan está cerrado',
    howWasPlan: '¿Cómo estuvo el plan?',
    yourOpinionHelps: 'Tu opinión ayuda a mejorar futuros eventos',
    votingClosesIn: 'La votación cierra 6 horas después del fin del plan',
    wantToLeavePlan: '¿Quieres salir de este plan?',
    youVotedBad: 'Votaste que no te gustó el plan',
    yesLeavePlan: 'Sí, salir del plan',
    noStayInGroup: 'No, permanecer en el grupo',
    adminActionsTitle: 'Acciones del Administrador',
    chooseWhatToDo: 'Elige qué hacer con este plan',
    renewPlanBtn: '🔄 Renovar Plan',
    terminatePlanBtn: '❌ Terminar Plan',
    cancel: 'Cancelar',
    terminatePlanTitle: 'Terminar Plan ❌',
    terminatePlanDesc: 'El plan se marcará como terminado y permanecerá visible durante 24 horas antes de eliminarse automáticamente.',
    terminateWarning: '⚠️ Esta acción no se puede deshacer. Todos los miembros verán que el plan fue terminado.',
    back: 'Volver',
    confirmTermination: 'Confirmar Terminación',
    renewPlanTitle: 'Renovar Plan 🔄',
    renewPlanDesc: 'Todo se renovará con nueva fecha y hora. Las experience stories anteriores se mantendrán.',
    newDate: 'Nueva Fecha',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Fin',
    newAddress: 'Nueva Dirección',
    fullAddress: 'Dirección completa',
    confirmRenewal: 'Confirmar Renovación',
    terminatePlanQuestion: '¿Cerrar Plan?',
    terminatePlanVisibleDesc: 'El plan se marcará como Cerrado y será visible para todos los miembros durante 24 horas, luego se eliminará automáticamente.',
    terminated: 'Cerrado',
    terminatePlanConfirm: 'Cerrar Plan',
    planRenewed: "🔄 ¡El plan ha sido renovado! Let's gooo 😎",
    planTerminatedMsg: '❌ El administrador ha cerrado este plan. El grupo será eliminado en 24 horas.',
    // Ambassador CTA
    ambassadorCtaTitle: '¡Sé el primero en tu ciudad!',
    ambassadorCtaDesc: 'No hay planes en {city} todavía. ¡Conviértete en Vybt Ambassador y trae el vibe a tu área!',
    becomeAmbassador: 'Convertirme en Ambassador',
    // Settings - Appearance & Privacy
    appearance: 'Apariencia',
    switchToLight: 'Cambiar a tema claro',
    switchToDark: 'Cambiar a tema oscuro',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    privateProfile: 'Perfil Privado',
    publicProfile: 'Perfil Público',
    privateProfileDesc: 'Solo los amigos pueden ver tus stories, planes y amigos',
    publicProfileDesc: 'Todo el mundo puede ver tu perfil completo',
    // GroupChat
    joinPlanToAccess: 'Únete al plan para acceder al grupo y chatear.',
    backBtn: '← Volver',
    planUpdated: '✏️ Plan actualizado',
    terminatedBanner: '❌ Terminado',
    happeningNowHeader: 'Su plan esta sucediendo ahora!'
  },

  fr: {
    name: 'Français',
    flag: '🇫🇷',
    // Onboarding
    continue: 'Continuer',
    whereAreYou: 'Où es-tu ? 📍',
    locationSubtitle: 'Nous te montrerons des plans et des personnes à proximité.',
    useMyLocation: 'Utiliser ma position actuelle',
    detecting: 'Détection...',
    tapToDetect: 'Appuie pour détecter automatiquement',
    locationSetTo: 'Localisation définie sur',
    chooseLanguage: 'Choisis ta langue 🌍',
    languageSubtitle: "Sélectionne la langue dans laquelle tu veux utiliser l'app.",
    whatsYourName: 'Comment tu t\'appelles ? 👋',
    nameSubtitle: "C'est ainsi que les autres utilisateurs te verront sur Vybt.",
    yourNamePlaceholder: 'Ton prénom...',
    whatsYourGender: 'Quel est ton genre ?',
    genderSubtitle: 'Cela nous aide à personnaliser ton expérience',
    female: 'Féminin',
    male: 'Masculin',
    other: 'Autre',
    whatsYourBirthday: "Quelle est ta date de naissance ?",
    birthdaySubtitle: 'Tu dois avoir 16+ ans pour utiliser Vybt',
    ageVerified: '✓ Âge vérifié',
    yearsOld: 'ans',
    mustBe16: 'Tu dois avoir au moins 16 ans pour utiliser Vybt',
    addYourPhotos: 'Ajoute tes photos',
    photosSubtitle: 'Au moins 1 photo est requise (première photo pour vérification)',
    mainPhoto: 'Principale (Obligatoire)',
    photo: 'Photo',
    photoVerificationWarning: 'Ta première photo sera utilisée pour la vérification du profil. Assure-toi qu\'elle montre clairement ton visage.',
    whatsYourVibe: "C'est quoi ton vibe ?",
    vibeSubtitle: 'Sélectionne {min}–{max} styles musicaux que tu adores',
    searchVibes: 'Rechercher des vibes...',
    vibesCount: 'vibes',
    selected: 'sélectionné',
    limitReached: 'Limite atteinte — désélectionne un pour en choisir un autre',
    whatPartiesDoYouLove: 'Quelles plans tu adores ?',
    partySubtitle: 'Sélectionne {min}–{max} types de fêtes',
    searchPartyTypes: 'Rechercher des types de fêtes...',
    typesCount: 'types',
    // Welcome complete
    welcomeTitle: 'Bienvenue !',
    accountReady: 'Ton compte est prêt',
    searchPlansTonight: 'Chercher des plans pour ce soir ?',
    explorePlansLocation: 'Explorer tous les plans dans ta région',
    letsGo: 'Allons-y ! 🎉',
    // Verification step
    verifyYourProfile: 'Vérifie ton profil',
    verifyDesc1: 'Prenez un selfie pour obtenir un ',
    verifyBadge: 'badge bleu vérifié',
    verifyDesc2: ' et renforcer la confiance des autres utilisateurs.',
    verifyNow: 'Vérifier Maintenant',
    skipForNow: 'Passer pour le moment',
    // Navigation
    home: 'Accueil',
    explore: 'Explorer',
    create: 'Créer',
    messages: 'Messages',
    profile: 'Profil',
    // BottomNav menu
    addStory: 'Ajouter une Story',
    createNewPlan: 'Créer un nouveau Plan',
    // Home
    myPlans: 'Mes Plans',
    seeAll: 'Voir tout',
    tonight: 'Ce Soir',
    forYou: 'Pour Toi',
    happeningNow: 'En ce Moment',
    // Profile
    myFriends: 'Mes Amis',
    joinedPartyPlans: 'Plans rejoints',
    myExperienceStories: 'Mes Histoires',
    profileVerified: 'Profil Vérifié ✓',
    verifyProfile: 'Vérifier mon Profil',
    verifyBadge: 'Obtiens un badge bleu pour inspirer confiance',
    friends: 'Amis',
    parties: 'Fêtes',
    stories: 'Histoires',
    ambassadorProgram: 'Programme Ambassadeur',
    allPerksUnlocked: 'Tous les avantages débloqués !',
    friendsInvited: 'amis invités',
    // Edit Profile
    editProfile: 'Modifier le Profil',
    photos: 'Photos (max 3)',
    displayName: "Nom d'affichage",
    bio: 'Bio',
    bioPlaceholder: 'Parle de toi aux autres...',
    dateOfBirth: 'Date de Naissance',
    age: 'Âge',
    yourLocation: 'Ta Localisation',
    detectingLocation: 'Détection de ta localisation...',
    tapToUseLocation: 'Appuie pour utiliser la position actuelle',
    searchRadius: 'Rayon de Recherche',
    yourVibes: 'Tes Vibes (max 5)',
    preferredPartyTypes: 'Types de Fêtes Préférés',
    saveChanges: 'Enregistrer les Modifications',
    main: 'Principale',
    // Settings
    settings: 'Paramètres',
    account: 'Compte',
    notifications: 'Notifications',
    manageAlerts: 'Gérer tes alertes',
    language: 'Langue',
    legalCommunity: 'Légal & Communauté',
    communityGuidelines: 'Règles de la Communauté',
    termsConditions: "Conditions d'Utilisation",
    privacyPolicy: 'Politique de Confidentialité',
    support: 'Support',
    helpFaq: 'Aide & FAQ',
    session: 'Session',
    logOut: 'Se Déconnecter',
    deleteAccount: 'Supprimer le Compte',
    deleteAccountSub: 'Supprimer définitivement tes données',
    chooseLanguageTitle: 'Choisir la Langue',
    administration: 'Administration',
    moderationPanel: 'Panneau de Modération',
    moderationSub: 'Examiner les signalements de contenu',
    // Explore
    plans: 'Plans',
    people: 'Personnes',
    map: 'Carte',
    searchPlans: 'Rechercher des plans...',
    searchPeople: 'Rechercher des personnes...',
    filters: 'Filtres',
    allTag: 'Tous',
    onFire: 'En Feu',
    mostMembers: 'Plus de Membres',
    matchesVibes: 'Correspond à Mes Vibes',
    noPlansFound: 'Aucun plan trouvé',
    noUsersFound: 'Aucun utilisateur trouvé',
    vibesMatch: 'vibes en commun',
    // Profile
    myVibes: 'Mes Vibes',
    preferredParties: 'Fêtes Préférées',
    // Friends
    friendsTab: 'Amis',
    requests: 'Demandes',
    noFriendsYet: 'Pas encore d\'amis',
    noPendingRequests: 'Pas de demandes en attente',
    wantsToBeYourFriend: 'Veut être ton ami',
    noLocation: 'Pas de localisation',
    // Notifications
    notifications_title: 'Notifications',
    unread: 'non lues',
    markAllRead: 'Tout marquer',
    noNotifications: 'Pas de notifications',
    removed: 'Supprimée',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    friendRequest: " je t'ai envoyé une demande d'ami.",
    // MyStories
    myExperienceStoriesTitle: 'Mes Histoires d\'Expérience',
    noStoriesYet: "Tu n'as pas encore partagé d'histoires",
    addFirstStory: 'Ajoute ta Première Histoire',
    unknownPlan: 'Plan Inconnu',
    // Plan Details
    going: 'Présent',
    groupChat: 'Chat de Groupe',
    joinPlan: 'Rejoindre le Plan',
    leavePlan: 'Quitter',
    about: 'À propos',
    experienceStories: "Histoires d'Expérience",
    shareYourExperience: 'Partage ton expérience',
    storiesUnavailableVoting: 'Histoires indisponibles pendant le vote',
    planLimitWarning: 'Tu as atteint la limite de 3 plans à',
    leaveToJoin: 'Quitte un plan pour rejoindre celui-ci.',
    votingActiveNotice: '🗳️ Période de vote active — Tu ne peux pas rejoindre ou quitter pendant le vote (6 heures)',
    planTerminated: '❌ Plan Terminé',
    planTerminatedDesc: 'Ce plan a été terminé par l\'administrateur et sera supprimé dans 24 heures',
    highlightPlan: 'Mettre en avant ce plan - €2.99',
    // Create Plan
    createNewPlanTitle: 'Créer un Nouveau Plan',
    // Add Story
    addStoryTitle: 'Ajouter une Story',
    whichPlanIsThisFor: 'Pour quel plan est-ce ?',
    noActivePlans: 'Pas encore de plans actifs.\nRejoins un plan et attends qu\'il commence.',
    shareStory: 'Partager la Story',
    processingChecking: 'Traitement et vérification du contenu...',
    // Story visibility
    friendsVisibility: 'Amis',
    groupOnly: 'Groupe',
    highlight: 'Mettre en avant',
    // Welcome page
    welcomeHero: 'Hé, l\'ami !',
    welcomeSubtitle: 'Rejoins-nous : connectons-nous et créons les meilleurs plans\ndans ta région !!!',
    downloadNow: 'Télécharger Maintenant !',
    allRightsReserved: 'Tous droits réservés.',
    // Group Chat
    votingOpen: 'Vote ouvert ! Appuie pour voter',
    awaitingAdminDecision: "⏳ En attente que l'administrateur renouvelle ou ferme le plan",
    renewPlan: 'Renouveler',
    terminatePlan: 'Fermer',
    beFirstToMessage: 'Sois le premier à envoyer un message !',
    chatLocked: "Chat verrouillé — en attente de la décision de l'administrateur",
    messagePlaceholder: 'Message...',
    adminActions: 'Actions Admin',
    editPlan: 'Modifier le Plan',
    editPlanUnavailableVoting: 'Indisponible pendant le vote',
    editPlanUnavailableEnded: 'Indisponible pendant que le plan est fermé',
    howWasPlan: 'Comment était le plan ?',
    yourOpinionHelps: 'Ton opinion aide à améliorer les futurs événements',
    votingClosesIn: 'Le vote ferme 6 heures après la fin du plan',
    wantToLeavePlan: 'Tu veux quitter ce plan ?',
    youVotedBad: "Tu as voté que tu n'as pas aimé le plan",
    yesLeavePlan: 'Oui, quitter le plan',
    noStayInGroup: 'Non, rester dans le groupe',
    adminActionsTitle: "Actions de l'Administrateur",
    chooseWhatToDo: 'Choisis quoi faire avec ce plan',
    renewPlanBtn: '🔄 Renouveler le Plan',
    terminatePlanBtn: '❌ Terminer le Plan',
    cancel: 'Annuler',
    terminatePlanTitle: 'Terminer le Plan ❌',
    terminatePlanDesc: 'Le plan sera marqué comme terminé et restera visible pendant 24 heures avant d\'être supprimé automatiquement.',
    terminateWarning: '⚠️ Cette action est irréversible. Tous les membres verront que le plan a été terminé.',
    back: 'Retour',
    confirmTermination: 'Confirmer la Résiliation',
    renewPlanTitle: 'Renouveler le Plan 🔄',
    renewPlanDesc: 'Tout sera renouvelé avec une nouvelle date et heure. Les experience stories précédentes seront conservées.',
    newDate: 'Nouvelle Date',
    startTime: 'Heure de Début',
    endTime: 'Heure de Fin',
    newAddress: 'Nouvelle Adresse',
    fullAddress: 'Adresse complète',
    confirmRenewal: 'Confirmer le Renouvellement',
    terminatePlanQuestion: 'Fermer le Plan ?',
    terminatePlanVisibleDesc: 'Le plan sera marqué comme Fermé et visible pour tous les membres pendant 24 heures, puis supprimé automatiquement.',
    terminated: 'Fermé',
    terminatePlanConfirm: 'Fermer le Plan',
    planRenewed: "🔄 Le plan a été renouvelé ! Let's gooo 😎",
    planTerminatedMsg: '❌ L\'administrateur a fermé ce plan. Le groupe sera supprimé dans 24 heures.',
    // Ambassador CTA
    ambassadorCtaTitle: 'Sois le premier dans ta ville !',
    ambassadorCtaDesc: 'Il n\'y a pas encore de plans à {city}. Deviens Vybt Ambassador et apporte le vibe dans ta région !',
    becomeAmbassador: 'Devenir Ambassador',
    // Settings - Appearance & Privacy
    appearance: 'Apparence',
    switchToLight: 'Passer au thème clair',
    switchToDark: 'Passer au thème sombre',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    privateProfile: 'Profil Privé',
    publicProfile: 'Profil Public',
    privateProfileDesc: 'Seuls tes amis voient tes stories, plans et amis',
    publicProfileDesc: 'Tout le monde peut voir ton profil complet',
    // GroupChat
    joinPlanToAccess: 'Rejoins le plan pour accéder au groupe et discuter.',
    backBtn: '← Retour',
    planUpdated: '✏️ Plan mis à jour',
    terminatedBanner: '❌ Terminé',
    happeningNowHeader: 'Votre plan est en train de se réaliser!'
  },

  it: {
    name: 'Italiano',
    flag: '🇮🇹',
    // Onboarding
    continue: 'Continua',
    whereAreYou: 'Dove sei? 📍',
    locationSubtitle: 'Ti mostreremo piani e persone nelle vicinanze.',
    useMyLocation: 'Usa la mia posizione attuale',
    detecting: 'Rilevamento...',
    tapToDetect: 'Tocca per rilevare automaticamente',
    locationSetTo: 'Posizione impostata su',
    chooseLanguage: 'Scegli la tua lingua 🌍',
    languageSubtitle: "Seleziona la lingua in cui vuoi usare l'app.",
    whatsYourName: 'Come ti chiami? 👋',
    nameSubtitle: 'È così che gli altri utenti ti vedranno su Vybt.',
    yourNamePlaceholder: 'Il tuo nome...',
    whatsYourGender: 'Qual è il tuo genere?',
    genderSubtitle: 'Questo ci aiuta a personalizzare la tua esperienza',
    female: 'Femmina',
    male: 'Maschio',
    other: 'Altro',
    whatsYourBirthday: 'Qual è il tuo compleanno?',
    birthdaySubtitle: 'Devi avere 16+ anni per usare Vybt',
    ageVerified: '✓ Età verificata',
    yearsOld: 'anni',
    mustBe16: 'Devi avere almeno 16 anni per usare Vybt',
    addYourPhotos: 'Aggiungi le tue foto',
    photosSubtitle: 'È richiesta almeno 1 foto (prima foto per la verifica)',
    mainPhoto: 'Principale (Obbligatoria)',
    photo: 'Foto',
    photoVerificationWarning: 'La tua prima foto verrà usata per la verifica del profilo. Assicurati che mostri chiaramente il tuo viso.',
    whatsYourVibe: "Qual è il tuo vibe?",
    vibeSubtitle: 'Seleziona {min}–{max} stili musicali che ami',
    searchVibes: 'Cerca vibes...',
    vibesCount: 'vibes',
    selected: 'selezionato',
    limitReached: 'Limite raggiunto — deseleziona uno per sceglierne un altro',
    whatPartiesDoYouLove: 'Che piani ami?',
    partySubtitle: 'Seleziona {min}–{max} tipi di feste',
    searchPartyTypes: 'Cerca tipi di feste...',
    typesCount: 'tipi',
    // Welcome complete
    welcomeTitle: 'Benvenuto!',
    accountReady: 'Il tuo account è pronto',
    searchPlansTonight: 'Cercare piani per stasera?',
    explorePlansLocation: 'Esplora tutti i piani nella tua zona',
    letsGo: 'Andiamo! 🎉',
    // Verification step
    verifyYourProfile: 'Verifica il tuo profilo',
    verifyDesc1: 'Scatta un selfie per ottenere un ',
    verifyBadge: 'badge blu di verifica',
    verifyDesc2: ' e costruire fiducia con gli altri utenti.',
    verifyNow: 'Verifica Ora',
    skipForNow: 'Salta per ora',
    // Navigation
    home: 'Home',
    explore: 'Esplora',
    create: 'Crea',
    messages: 'Messaggi',
    profile: 'Profilo',
    // BottomNav menu
    addStory: 'Aggiungi Story',
    createNewPlan: 'Crea nuovo Piano',
    // Home
    myPlans: 'Miei Piani',
    seeAll: 'Vedi tutto',
    tonight: 'Stasera',
    forYou: 'Per Te',
    happeningNow: 'In Corso Ora',
    // Profile
    myFriends: 'I Miei Amici',
    joinedPartyPlans: 'Piani a cui ho partecipato',
    myExperienceStories: 'Le Mie Storie',
    profileVerified: 'Profilo Verificato ✓',
    verifyProfile: 'Verifica il Mio Profilo',
    verifyBadge: 'Ottieni un badge blu per aumentare la fiducia',
    friends: 'Amici',
    parties: 'Feste',
    stories: 'Storie',
    ambassadorProgram: 'Programma Ambasciatore',
    allPerksUnlocked: 'Tutti i vantaggi sbloccati!',
    friendsInvited: 'amici invitati',
    // Edit Profile
    editProfile: 'Modifica Profilo',
    photos: 'Foto (max 3)',
    displayName: 'Nome visualizzato',
    bio: 'Bio',
    bioPlaceholder: 'Racconta qualcosa di te...',
    dateOfBirth: 'Data di Nascita',
    age: 'Età',
    yourLocation: 'La Tua Posizione',
    detectingLocation: 'Rilevamento della tua posizione...',
    tapToUseLocation: 'Tocca per usare la posizione attuale',
    searchRadius: 'Raggio di Ricerca',
    yourVibes: 'I Tuoi Vibes (max 5)',
    preferredPartyTypes: 'Tipi di Feste Preferiti',
    saveChanges: 'Salva Modifiche',
    main: 'Principale',
    // Settings
    settings: 'Impostazioni',
    account: 'Account',
    notifications: 'Notifiche',
    manageAlerts: 'Gestisci i tuoi avvisi',
    language: 'Lingua',
    legalCommunity: 'Legale & Comunità',
    communityGuidelines: 'Linee Guida della Comunità',
    termsConditions: 'Termini e Condizioni',
    privacyPolicy: 'Informativa sulla Privacy',
    support: 'Supporto',
    helpFaq: 'Aiuto & FAQ',
    session: 'Sessione',
    logOut: 'Esci',
    deleteAccount: "Elimina l'Account",
    deleteAccountSub: 'Rimuovi definitivamente i tuoi dati',
    chooseLanguageTitle: 'Scegli la Lingua',
    administration: 'Amministrazione',
    moderationPanel: 'Pannello di Moderazione',
    moderationSub: 'Esamina le segnalazioni di contenuto',
    // Explore
    plans: 'Piani',
    people: 'Persone',
    map: 'Mappa',
    searchPlans: 'Cerca piani...',
    searchPeople: 'Cerca persone...',
    filters: 'Filtri',
    allTag: 'Tutti',
    onFire: 'In Fiamme',
    mostMembers: 'Più Membri',
    matchesVibes: 'Corrisponde ai Miei Vibes',
    noPlansFound: 'Nessun piano trovato',
    noUsersFound: 'Nessun utente trovato',
    vibesMatch: 'vibes in comune',
    // Profile
    myVibes: 'I Miei Vibes',
    preferredParties: 'Feste Preferite',
    // Friends
    friendsTab: 'Amici',
    requests: 'Richieste',
    noFriendsYet: 'Ancora nessun amico',
    noPendingRequests: 'Nessuna richiesta in attesa',
    wantsToBeYourFriend: 'Vuole essere tuo amico',
    noLocation: 'Nessuna posizione',
    // Notifications
    notifications_title: 'Notifiche',
    unread: 'non lette',
    markAllRead: 'Segna tutte',
    noNotifications: 'Nessuna notifica',
    removed: 'Rimossa',
    confirm: 'Confermare',
    delete: 'Eliminare',
    friendRequest: " ti ho mandato una richiesta di amicizia.",
    // MyStories
    myExperienceStoriesTitle: 'Le Mie Storie di Esperienza',
    noStoriesYet: 'Non hai ancora condiviso nessuna storia',
    addFirstStory: 'Aggiungi la Tua Prima Storia',
    unknownPlan: 'Piano Sconosciuto',
    // Plan Details
    going: 'Presente',
    groupChat: 'Chat di Gruppo',
    joinPlan: 'Unisciti al Piano',
    leavePlan: 'Lascia',
    about: 'Info',
    experienceStories: 'Storie di Esperienza',
    shareYourExperience: 'Condividi la tua esperienza',
    storiesUnavailableVoting: 'Storie non disponibili durante la votazione',
    planLimitWarning: 'Hai raggiunto il limite di 3 piani a',
    leaveToJoin: 'Lascia un piano per unirti a questo.',
    votingActiveNotice: '🗳️ Periodo di votazione attivo — Non puoi unirti o uscire durante la votazione (6 ore)',
    planTerminated: '❌ Piano Terminato',
    planTerminatedDesc: 'Questo piano è stato terminato dall\'amministratore e verrà eliminato in 24 ore',
    highlightPlan: 'Metti in evidenza questo piano - €2.99',
    // Create Plan
    createNewPlanTitle: 'Crea Nuovo Piano',
    // Add Story
    addStoryTitle: 'Aggiungi Story',
    whichPlanIsThisFor: 'Per quale piano è questa?',
    noActivePlans: 'Nessun piano attivo ancora.\nUnisciti a un piano e aspetta che inizi.',
    shareStory: 'Condividi Story',
    processingChecking: 'Elaborazione e verifica del contenuto...',
    // Story visibility
    friendsVisibility: 'Amici',
    groupOnly: 'Gruppo',
    highlight: 'Evidenzia',
    // Welcome page
    welcomeHero: 'Ehi, amico!',
    welcomeSubtitle: 'Unisciti a noi: connettiamoci e creiamo i migliori piani\nnella tua zona!!!',
    downloadNow: 'Scarica Ora!',
    allRightsReserved: 'Tutti i diritti riservati.',
    // Group Chat
    votingOpen: 'Votazione aperta! Tocca per votare',
    awaitingAdminDecision: "⏳ In attesa che l'amministratore rinnovi o chiuda il piano",
    renewPlan: 'Rinnova',
    terminatePlan: 'Chiudi',
    beFirstToMessage: 'Sii il primo a inviare un messaggio!',
    chatLocked: "Chat bloccata — in attesa della decisione dell'amministratore",
    messagePlaceholder: 'Messaggio...',
    adminActions: 'Azioni Admin',
    editPlan: 'Modifica Piano',
    editPlanUnavailableVoting: 'Non disponibile durante la votazione',
    editPlanUnavailableEnded: 'Non disponibile mentre il piano è chiuso',
    howWasPlan: 'Com\'era il piano?',
    yourOpinionHelps: 'La tua opinione aiuta a migliorare i futuri eventi',
    votingClosesIn: 'La votazione si chiude 6 ore dopo la fine del piano',
    wantToLeavePlan: 'Vuoi lasciare questo piano?',
    youVotedBad: 'Hai votato che non ti è piaciuto il piano',
    yesLeavePlan: 'Sì, lascia il piano',
    noStayInGroup: 'No, rimani nel gruppo',
    adminActionsTitle: "Azioni dell'Amministratore",
    chooseWhatToDo: 'Scegli cosa fare con questo piano',
    renewPlanBtn: '🔄 Rinnova Piano',
    terminatePlanBtn: '❌ Termina Piano',
    cancel: 'Annulla',
    terminatePlanTitle: 'Termina Piano ❌',
    terminatePlanDesc: 'Il piano sarà contrassegnato come terminato e rimarrà visibile per 24 ore prima di essere eliminato automaticamente.',
    terminateWarning: '⚠️ Questa azione non può essere annullata. Tutti i membri vedranno che il piano è stato terminato.',
    back: 'Indietro',
    confirmTermination: 'Conferma Terminazione',
    renewPlanTitle: 'Rinnova Piano 🔄',
    renewPlanDesc: 'Tutto verrà rinnovato con nuova data e orario. Le experience stories precedenti verranno mantenute.',
    newDate: 'Nuova Data',
    startTime: 'Orario di Inizio',
    endTime: 'Orario di Fine',
    newAddress: 'Nuovo Indirizzo',
    fullAddress: 'Indirizzo completo',
    confirmRenewal: 'Conferma Rinnovo',
    terminatePlanQuestion: 'Chiudere il Piano?',
    terminatePlanVisibleDesc: 'Il piano sarà contrassegnato come Chiuso e visibile a tutti i membri per 24 ore, poi rimosso automaticamente.',
    terminated: 'Chiuso',
    terminatePlanConfirm: 'Chiudi Piano',
    planRenewed: "🔄 Il piano è stato rinnovato! Let's gooo 😎",
    planTerminatedMsg: '❌ L\'amministratore ha chiuso questo piano. Il gruppo verrà rimosso in 24 ore.',
    // Ambassador CTA
    ambassadorCtaTitle: 'Sii il primo nella tua città!',
    ambassadorCtaDesc: 'Non ci sono ancora piani a {city}. Diventa Vybt Ambassador e porta il vibe nella tua area!',
    becomeAmbassador: 'Diventare Ambassador',
    // Settings - Appearance & Privacy
    appearance: 'Aspetto',
    switchToLight: 'Passa al tema chiaro',
    switchToDark: 'Passa al tema scuro',
    darkMode: 'Modalità Scura',
    lightMode: 'Modalità Chiara',
    privateProfile: 'Profilo Privato',
    publicProfile: 'Profilo Pubblico',
    privateProfileDesc: 'Solo gli amici vedono le tue storie, piani e amici',
    publicProfileDesc: 'Tutti possono vedere il tuo profilo completo',
    // GroupChat
    joinPlanToAccess: 'Unisciti al piano per accedere al gruppo e chattare.',
    backBtn: '← Indietro',
    planUpdated: '✏️ Piano aggiornato',
    terminatedBanner: '❌ Terminato',
    happeningNowHeader: 'Il tuo piano si sta realizzando proprio ora!'
    
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  React.useEffect(() => {
    const handler = () => {
      const lang = localStorage.getItem('app_language') || 'en';
      setLanguage(lang);
    };
    window.addEventListener('languagechange', handler);
    return () => window.removeEventListener('languagechange', handler);
  }, []);

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}