import React, { createContext, useContext, useState } from 'react';

export const translations = {
  pt: {
    name: 'Português',
    flag: '🇵🇹',
    // Onboarding
    continue: 'Continuar',
    whereAreYou: 'Onde voce está? 📍',
    locationSubtitle: 'Vamos te mostrar planos e pessoas perto de você.',
    useMyLocation: 'Usar minha localização atual',
    detecting: 'Detectando...',
    tapToDetect: 'Toque para detectar automaticamente',
    locationSetTo: 'Localização definida para',
    chooseLanguage: 'Escolha o teu idioma 🌍',
    languageSubtitle: 'Selecione o idioma que quer usar.',
    whatsYourName: 'Qual seu nome? 👋',
    nameSubtitle: 'É assim que outros utilizadores vão te ver na Vybt.',
    yourNamePlaceholder: 'O seu nome...',
    whatsYourGender: 'Qual seu género?',
    genderSubtitle: 'Nos ajude a personalizar a sua experiência',
    female: 'Feminino',
    male: 'Masculino',
    other: 'Outro',
    whatsYourBirthday: 'Qual sua data de nascimento?',
    birthdaySubtitle: 'Você precisa ter 16+ anos para entrar na Vybt',
    ageVerified: '✓ Idade verificada',
    yearsOld: 'anos',
    mustBe16: 'Você precisa ter pelo menos 16 anos para usar a Vybt',
    addYourPhotos: 'Adicione as suas fotos',
    photosSubtitle: 'Precisa pelo menos de 1 foto (primeira foto para verificação)',
    mainPhoto: 'Principal (Obrigatória)',
    photo: 'Foto',
    photoVerificationWarning: 'A sua primeira foto será usada para verificação do perfil. Certifique-se que seu rosto está 100% visível.',
    whatsYourVibe: 'Qual é a sua vibe?',
    vibeSubtitle: 'Selecione {min}–{max} estilos musicais que curte',
    searchVibes: 'Pesquise as diferentes vibes...',
    vibesCount: 'vibes',
    selected: 'selecionado',
    limitReached: 'Limite atingido — remove um para escolher outro',
    whatPartiesDoYouLove: 'Qual o seu tipo de festa?',
    partySubtitle: 'Seleciona {min}–{max} tipos de festas',
    searchPartyTypes: 'Pesquisar tipos de festas...',
    typesCount: 'tipos',
    // Welcome complete
    welcomeTitle: 'Bem-vindo!',
    accountReady: 'A sua conta está pronta',
    searchPlansTonight: 'Pesquisar planos para esta noite?',
    explorePlansLocation: 'Explorar todos os planos na sua localização',
    letsGo: "Vamos lá! 🎉",
    // Verification step
    verifyYourProfile: 'Verifica o seu perfil',
    verifyDesc1: 'Tire uma selfie para conseguir o ',
    verifyBadge: 'selo azul de verificação',
    verifyDesc2: ' e construir confiança com outros usuários.',
    verifyNow: 'Verificar Agora',
    skipForNow: 'Deixar pra Depois',
    // Navigation
    home: 'Início',
    explore: 'Explorar',
    create: 'Criar',
    messages: 'Mensagens',
    profile: 'Perfil',
    // BottomNav menu
    addStory: 'Adicionar Story',
    createNewPlan: 'Criar novo Plano',
    // Home
    myPlans: 'Meus Planos',
    seeAll: 'Ver tudo',
    tonight: 'Esta Noite',
    forYou: 'Para Você',
    happeningNow: 'Acontecendo Agora',
    // Profile
    myFriends: 'Meus Amigos',
    joinedPartyPlans: 'Planos que Participei',
    myExperienceStories: 'Meus Stories',
    profileVerified: 'Perfil Verificado ✓',
    verifyProfile: 'Verificar o Meu Perfil',
    friends: 'Amigos',
    stories: 'Stories',
    // Edit Profile
    editProfile: 'Editar Perfil',
    photos: 'Fotos (máximo 5) — a primeira é a foto de perfil.',
    displayName: 'Nome de Exibição',
    bio: 'Bio',
    bioPlaceholder: 'Fale mais sobre você...',
    dateOfBirth: 'Data de Nascimento',
    yourLocation: 'Sua Localização',
    detectingLocation: 'Detectando sua localização...',
    tapToUseLocation: 'Toque para usar a localização atual',
    searchRadius: 'Raio de Pesquisa',
    yourVibes: 'Suas Vibes (máx. 5)',
    preferredPartyTypes: 'Tipos de Festas Preferidas',
    saveChanges: 'Guardar Alterações',
    // Settings
    settings: 'Definições',
    account: 'Conta',
    notifications: 'Notificações',
    manageAlerts: 'Gerir os teus alertas',
    language: 'Idioma',
    legalCommunity: 'Termos Legais & Comunidade',
    communityGuidelines: 'Diretrizes da Comunidade',
    termsConditions: 'Termos e Condições',
    privacyPolicy: 'Política de Privacidade',
    support: 'Suporte',
    helpFaq: 'Ajuda & FAQ',
    session: 'Sessão',
    logOut: 'Terminar Sessão',
    deleteAccount: 'Eliminar Conta',
    deleteAccountSub: 'Remover permanentemente os seus dados',
    chooseLanguageTitle: 'Escolher Idioma',
    administration: 'Administração',
    moderationPanel: 'Painel de Moderação',
    moderationSub: 'Rever denúncias de conteúdo',
    // Explore
    plans: 'Planos',
    groups: 'Grupos',
    people: 'Pessoas',
    searchPlans: 'Pesquisar planos...',
    searchGroups: 'Pesquisar grupos...',
    searchPeople: 'Pesquisar pessoas...',
    filterPlans: 'Filtrar Planos',
    filterPeople: 'Filtrar Pessoas',
    allTag: 'Todos',
    onFire: 'Em Destaque',
    mostMembers: 'Mais Membros',
    matchesVibes: 'Combina com as Minhas Vibes',
    noPlansFound: 'Nenhum plano encontrado',
    noUsersFound: 'Nenhum utilizador encontrado',
    // Friends
    requests: 'Pedidos',
    noFriendsYet: 'Sem amigos ainda',
    noPendingRequests: 'Sem pedidos pendentes',
    wantsToBeYourFriend: 'Quer ser seu amigo',
    noLocation: 'Sem localização',
    // Notifications
    markAllRead: 'Marcar todas',
    removed: 'Removido',
    confirm: 'Confirmar',
    delete: 'Deletar',
    friendRequest: ' te enviou um pedido de amizade.',
    // MyStories
    noStoriesYet: 'Ainda não tem nenhum story compartilhado',
    addFirstStory: 'Adiciona Seu Primeiro Story',
    unknownPlan: 'Plano Desconhecido',
    // Plan Details
    going: 'Indo',
    groupChat: 'Chat do Grupo',
    joinPlan: 'Entrar no Plano',
    leavePlan: 'Sair',
    about: 'Sobre',
    experienceStories: 'Momentos',
    shareYourExperience: 'Compartilhe uma experiência incrível',
    storiesUnavailableVoting: 'Stories ficam indisponíveis durante a votação',
    planLimitWarning: 'Atingiu o limite de 3 planos em',
    leaveToJoin: 'Saia de um plano para entrar neste.',
    votingActiveNotice: '🗳️ Período de votação ativo — Não é possível entrar ou sair durante a votação (6 horas)',
    planTerminated: '❌ Plano Terminado',
    planTerminatedDesc: 'Este plano foi terminado pelo administrador e será eliminado em 24 horas',
    highlightPlan: 'Destacar este plano - €2.99',
    // Story visibility
    friendsVisibility: 'Amigos',
    groupOnly: 'Grupo',
    // Welcome page
    welcomeHero: 'Olá!',
    welcomeSubtitle: 'Vem com a gente: vamos te ajudar a encontrar e criar os melhores planos na sua cidade!!!',
    downloadNow: 'Faça o Download Agora!',
    allRightsReserved: 'Todos os direitos reservados.',
    // Group Chat
    votingOpen: 'Votação aberta! Toque para votar',
    awaitingAdminDecision: '⏳ Aguardando que o administrador renove ou encerre o plano',
    renewPlan: 'Renovar',
    terminatePlan: 'Encerrar',
    beFirstToMessage: 'Comece a conversa! Não tenha vergonha',
    chatLocked: 'Chat bloqueado — aguardando decisão do administrador',
    messagePlaceholder: 'Mensagem...',
    // Admin actions
    adminActions: 'Ações Admin',
    editPlan: 'Editar Plano',
    editPlanUnavailableVoting: 'Indisponível durante a votação',
    editPlanUnavailableEnded: 'Indisponível enquanto o plano está encerrado',
    // Voting modal
    howWasPlan: 'Como foi o plano?',
    yourOpinionHelps: 'A tua opinião ajuda a melhorar eventos futuros',
    votingClosesIn: 'Votação encerra 6 horas após o fim do plano',
    wantToLeavePlan: 'Quer sair desse plano?',
    youVotedBad: 'Votou que não gostou do plano',
    yesLeavePlan: 'Sim, sair do plano',
    noStayInGroup: 'Não, permanecer no grupo',
    // Renew plan modal
    adminActionsTitle: 'Ações do Administrador',
    chooseWhatToDo: 'Escolhe o que fazer com este plano',
    renewPlanBtn: '🔄 Renovar Plano',
    terminatePlanBtn: '❌ Terminar Plano',
    cancel: 'Cancelar',
    terminatePlanTitle: 'Terminar Plano ❌',
    terminatePlanDesc: 'O plano será marcado como terminado e ficará visível por 24 horas antes de ser eliminado automaticamente.',
    terminateWarning: '⚠️ Esta ação não pode ser desfeita. Todos os membros verão que o plano foi terminado.',
    back: 'Voltar',
    confirmTermination: 'Confirmar Término',
    renewPlanTitle: 'Renovar Plano 🔄',
    renewPlanDesc: 'Tudo será renovado com nova data e horário. As experience stories anteriores serão mantidas.',
    newDate: 'Nova Data',
    startTime: 'Horário de Início',
    endTime: 'Horário de Término',
    newAddress: 'Novo Endereço',
    fullAddress: 'Endereço completo',
    confirmRenewal: 'Confirmar Renovação',
    // Delete plan modal
    terminatePlanQuestion: 'Encerrar Plano?',
    terminatePlanVisibleDesc: 'O plano será marcado como Encerrado e ficará visível para todos os membros por 24 horas, depois será removido automaticamente.',
    terminatePlanConfirm: 'Encerrar Plano',
    // Plan renewed chat message
    planRenewed: '🔄 O plano foi renovado! Let\'s gooo 😎',
    planTerminatedMsg: '❌ O administrador encerrou este plano. O grupo será removido em 24 horas.',
    // Settings - Appearance & Privacy
    appearance: 'Aparência',
    switchToLight: 'Mudar para tema claro',
    switchToDark: 'Mudar para tema escuro',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    privateProfile: 'Perfil Privado',
    publicProfile: 'Perfil Público',
    privateProfileDesc: 'Só amigos vêem os seus stories, planos e amigos',
    publicProfileDesc: 'Todo mundo pode ver o seu perfil completo',
    // GroupChat
    joinPlanToAccess: 'Junte-se ao plano para entrar no grupo e conversar.',
    backBtn: '← Voltar',
    planUpdated: '✏️ Plano atualizado',
    terminatedBanner: '❌ Terminado',
    live: '🔵 Ao Vivo',
    add: 'Adicionar',
    you: 'Você',
    user: 'Usuário',
    members: 'Membros',
    viewGroup: 'Ver Grupo →',
    pinned: '📌 Fixado',
    notPinned: 'Não Fixado',
    noStoriesToPin: 'Sem Stories para Fixar',
    noMessagesToPin: 'Sem Mensagens para Fixar',
    inviteFriends: 'Convidar Amigos',
    noFriendsToInvite: 'Sem Amigos para Convidar',
    sent: 'Enviado',
    invite: 'Convidar',
    admin: 'Administrador',
    gallery: '📸 Galeria',
    noSharedMemories: 'Nenhuma Memória Compartilhada Ainda',
    downloading: 'Baixando...',
    download: 'Baixar',
    noStickersYet: 'Ainda não há stickers. Adicione o seu primeiro!',
    searchAddress: 'Procurar endereço...',
    setCity: 'Definir Cidade',
    kmradius: 'km raio',
    chooseCityDescription: 'Escolha a cidade para ver planos perto de você',
    chooseYourCity: 'ou escolha sua cidade',
    searchCity: '🔍 Procurar cidade...',
    select: 'Selecione...',
    member: 'Membro',
    aboutCommunity: 'Sobre esta Comunidade',
    active: 'Ativo',
    adminsCreatePlans: 'Admins criam planos',
    plansApproval: 'Planos precisam de aprovação',
    anyoneCreatePlans: 'Qualquer um pode criar planos',
    someone: 'Alguém',
    joinedAsAdmin: 'entrou como Admin',
    joinedCommunity: 'entrou na comunidade',
    newPlan: 'Novo plano',
    planCreated: 'plano criado',
    postedStory: 'publicou um story',
    communityStats: 'Estatísticas da Comunidade',
    newMembersWeek: 'Novos Membros\nesta semana',
    storiesWeek: 'Stories\nesta semana',
    upcomingPlans: 'Planos\nchegando',
    totalMembers: 'Total de Membros',
    joinedLast30d: 'Entrou nos últimos 30d',
    liveActivity: 'Atividade ao vivo',
    noActivityYet: 'Sem atividade ainda',
    noActivityDesc: 'A atividade vai aparecer aqui assim que os membros entrarem e participarem',
    challengeNight: '🌙 Desafio Noturno',
    challengeDay: '☀️ Desafio Diurno',
    challengeWeekend: '🎉 Desafio de Fim de Semana',
    challengeCustom: '⚡ Desafio',
    challengeTimeLeft: 'restantes',
    challengeEnded: 'Desafio encerrado',
    challengeTapToParticipate: '📸 Toque para ver e participar →',
    storiesSubmitted: 'stories enviados',
    challengeWinner: 'Vencedor',
    challengePostToParticipate: '📸 Publique o teu Story para participar',
    challengeFinalLeaderboard: '🏅 Classificação Final',
    challengeLiveLeaderboard: '📊 Classificação ao Vivo',
    storySingular: 'story',
    storiesPlural: 'stories',
    views: 'visualizações',
    challengePickWinner: 'Escolher Vencedor',
    challengeBeFirst: 'Seja o primeiro a participar!',
    createChallenge: 'Criar Desafio',
    createChallengeSubtitle: 'Anuncie um desafio de stories pra comunidade',
    challengePickEmoji: 'Escolha um emoji',
    challengeType: 'Tipo',
    challengeTypeNight: 'Noite',
    challengeTypeNightDesc: 'Melhor story da noite',
    challengeTypeDay: 'Dia',
    challengeTypeDayDesc: 'Melhor story do dia',
    challengeTypeWeekend: 'Fim de Semana',
    challengeTypeWeekendDesc: 'Vibe de fim de semana',
    challengeTypeCustom: 'Personalizado',
    challengeTypeCustomDesc: 'Seu próprio tema',
    challengeTitle: 'Título',
    challengeTitlePlaceholder: 'ex: Melhor foto do pôr do sol hoje 🌅',
    challengeDescription: 'Descrição',
    challengeDescriptionPlaceholder: 'Conta pra galera que tipo de story você quer ver...',
    challengeDuration: 'Duração',
    challengeDurationWeek: '1 semana',
    challengePrize: 'Prêmio / Recompensa',
    challengePrizePlaceholder: 'ex: Destaque na página da comunidade 🏆',
    challengeLinkPlan: 'Vincular a um Plano',
    challengeNoSpecificPlan: 'Nenhum plano específico',
    challengeLaunch: 'Lançar Desafio',
    challengeNewNotifTitle: 'Novo Desafio',
    challengeNewNotifMessage: 'Um novo desafio foi lançado! Poste seu story pra participar.',
    optional: 'opcional',
    editCommunity: 'Editar Comunidade',
    communityName: 'Nome',
    communityThemeColor: 'Cor do Tema',
    communityCoverImage: 'Foto de Capa',
    communityChangePhoto: 'Trocar foto',
    communityCoverPhoto: 'Foto de capa',
    communityBackgroundImage: 'Imagem de Fundo',
    communityBackgroundTexture: 'Textura de fundo',
    communityVisibility: 'Visibilidade',
    communityPrivateDesc: 'Privada — escondida do Início e do Explorar',
    communityPublicDesc: 'Pública — visível pra todo mundo',
    communityChatAccess: 'Acesso ao Chat',
    communityOpenToAll: 'Aberto pra todos',
    communityPlanPolicy: 'Política de Criação de Planos',
    policyAnyone: 'Qualquer um',
    policyApproval: 'Precisa de Aprovação',
    policyAdminsOnly: 'Só Admins',
    deleteCommunity: 'Deletar Comunidade',
    leave: 'Sair',
    reportCommunity: 'Denunciar Comunidade',
    join: 'Entrar 🚀',
    membersCount: 'membros',
    topMembers: 'Top Membros',
    total: 'total',
    guideStep1Title: 'Bem-vindo à Comunidade!',
    guideStep1Desc: 'Agora voce faz parte da comunidade. Aqui vai um guia rápido pra começar.',
    guideStep2Title: 'Entre e Crie Planos',
    guideStep2Desc: 'Veja os planos na aba Planos. Entre nos eventos ou crie o seu próprio!',
    guideStep3Title: 'Compartilhe Stories',
    guideStep3Desc: 'Depois de ir a um plano, poste stories pra mostrar sua vibe à comunidade.',
    guideStep4Title: 'Conheça os Membros',
    guideStep4Desc: 'Vai à aba de Membros pra ver quem está ativo e descobrir quem é o maior rolezeiro.',
    guideNext: 'Próximo',
    guideLetsGo: "Vamos lá! 🚀",
    guideBack: 'Voltar',
    eventStories: 'Stories do Evento',
    moreStories: 'mais stories',
    leaveCommunityTitle: 'Sair da Comunidade?',
    leaveCommunityConfirm: 'Tem a certeza que quer sair de',
    sortBy: 'Ordenar por',
    startTime: 'Hora de início',
    radius: 'Raio',
    partyType: 'Tipo de festa',
    search: 'Pesquisar...',
    clearFilters: 'Limpar filtros',
    showMe: 'Mostrar',
    ageRange: 'Faixa etária',
    city: 'Cidade',
    searchCityPlaceholder: 'Pesquisar por cidade...',
    vybtPlusCity: 'Explore utilizadores de qualquer cidade com Vybt Plus',
    similarVibes: 'Vibes semelhantes',
  },

en: {
    name: 'English',
    flag: '🇬🇧',
    // Onboarding
    continue: 'Continue',
    whereAreYou: 'Where are you? 📍',
    locationSubtitle: "We'll show you plans and people near you.",
    useMyLocation: 'Use my current location',
    detecting: 'Detecting...',
    tapToDetect: 'Tap to detect automatically',
    locationSetTo: 'Location set to',
    chooseLanguage: 'Choose your language 🌍',
    languageSubtitle: 'Select the language you want to use.',
    whatsYourName: "What's your name? 👋",
    nameSubtitle: 'This is how other users will see you on Vybt.',
    yourNamePlaceholder: 'Your name...',
    whatsYourGender: "What's your gender?",
    genderSubtitle: 'Help us personalize your experience',
    female: 'Female',
    male: 'Male',
    other: 'Other',
    whatsYourBirthday: "What's your birthday?",
    birthdaySubtitle: 'You need to be 16+ to join Vybt',
    ageVerified: '✓ Age verified',
    yearsOld: 'years old',
    mustBe16: 'You need to be at least 16 years old to use Vybt',
    addYourPhotos: 'Add your photos',
    photosSubtitle: 'At least 1 photo is required (first photo for verification)',
    mainPhoto: 'Main (Required)',
    photo: 'Photo',
    photoVerificationWarning: 'Your first photo will be used for profile verification. Make sure your face is 100% visible.',
    whatsYourVibe: "What's your vibe?",
    vibeSubtitle: 'Select {min}–{max} music styles you vibe with',
    searchVibes: 'Search the different vibes...',
    vibesCount: 'vibes',
    selected: 'selected',
    limitReached: 'Limit reached — remove one to pick another',
    whatPartiesDoYouLove: "What's your type of party?",
    partySubtitle: 'Select {min}–{max} party types',
    searchPartyTypes: 'Search party types...',
    typesCount: 'types',
    // Welcome complete
    welcomeTitle: 'Welcome!',
    accountReady: 'Your account is ready',
    searchPlansTonight: 'Search for plans tonight?',
    explorePlansLocation: 'Explore all plans in your area',
    letsGo: "Let's go! 🎉",
    // Verification step
    verifyYourProfile: 'Verify your profile',
    verifyDesc1: 'Take a selfie to get your ',
    verifyBadge: 'blue verified badge',
    verifyDesc2: ' and build trust with other users.',
    verifyNow: 'Verify Now',
    skipForNow: 'Do it Later',
    // Navigation
    home: 'Home',
    explore: 'Explore',
    create: 'Create',
    messages: 'Messages',
    profile: 'Profile',
    // BottomNav menu
    addStory: 'Add Story',
    createNewPlan: 'Create new Plan',
    // Home
    myPlans: 'My Plans',
    seeAll: 'See all',
    tonight: 'Tonight',
    forYou: 'For You',
    happeningNow: 'Happening Now',
    // Profile
    myFriends: 'My Friends',
    joinedPartyPlans: 'Plans I Joined',
    myExperienceStories: 'My Stories',
    profileVerified: 'Profile Verified ✓',
    verifyProfile: 'Verify My Profile',
    friends: 'Friends',
    stories: 'Stories',
    // Edit Profile
    editProfile: 'Edit Profile',
    photos: 'Photos (max 5) — first one is your profile pic.',
    displayName: 'Display Name',
    bio: 'Bio',
    bioPlaceholder: 'Tell us more about you...',
    dateOfBirth: 'Date of Birth',
    yourLocation: 'Your Location',
    detectingLocation: 'Detecting your location...',
    tapToUseLocation: 'Tap to use current location',
    searchRadius: 'Search Radius',
    yourVibes: 'Your Vibes (max 5)',
    preferredPartyTypes: 'Preferred Party Types',
    saveChanges: 'Save Changes',
    // Settings
    settings: 'Settings',
    account: 'Account',
    notifications: 'Notifications',
    manageAlerts: 'Manage your alerts',
    language: 'Language',
    legalCommunity: 'Legal & Community',
    communityGuidelines: 'Community Guidelines',
    termsConditions: 'Terms and Conditions',
    privacyPolicy: 'Privacy Policy',
    support: 'Support',
    helpFaq: 'Help & FAQ',
    session: 'Session',
    logOut: 'Log Out',
    deleteAccount: 'Delete Account',
    deleteAccountSub: 'Permanently remove your data',
    chooseLanguageTitle: 'Choose Language',
    administration: 'Administration',
    moderationPanel: 'Moderation Panel',
    moderationSub: 'Review content reports',
    // Explore
    plans: 'Plans',
    groups: 'Groups',
    people: 'People',
    searchPlans: 'Search plans...',
    searchGroups: 'Search groups...',
    searchPeople: 'Search people...',
    filterPlans: 'Filter Plans',
    filterPeople: 'Filter People',
    allTag: 'All',
    onFire: 'On Fire',
    mostMembers: 'Most Members',
    matchesVibes: 'Matches My Vibes',
    noPlansFound: 'No plans found',
    noUsersFound: 'No users found',
    // Friends
    requests: 'Requests',
    noFriendsYet: 'No friends yet',
    noPendingRequests: 'No pending requests',
    wantsToBeYourFriend: 'Wants to be your friend',
    noLocation: 'No location',
    // Notifications
    markAllRead: 'Mark all',
    removed: 'Removed',
    confirm: 'Confirm',
    delete: 'Delete',
    friendRequest: ' sent you a friend request.',
    // MyStories
    noStoriesYet: "You haven't shared any stories yet",
    addFirstStory: 'Add Your First Story',
    unknownPlan: 'Unknown Plan',
    // Plan Details
    going: 'Going',
    groupChat: 'Group Chat',
    joinPlan: 'Join Plan',
    leavePlan: 'Leave',
    about: 'About',
    experienceStories: 'Experiences',
    shareYourExperience: 'Share an amazing experience',
    storiesUnavailableVoting: 'Stories unavailable during voting',
    planLimitWarning: "You've hit the limit of 3 plans in",
    leaveToJoin: 'Leave a plan to join this one.',
    votingActiveNotice: '🗳️ Voting period active — You cannot join or leave during voting (6 hours)',
    planTerminated: '❌ Plan Terminated',
    planTerminatedDesc: 'This plan was terminated by the admin and will be deleted in 24 hours',
    highlightPlan: 'Highlight this plan - €2.99',
    // Story visibility
    friendsVisibility: 'Friends',
    groupOnly: 'Group',
    // Welcome page
    welcomeHero: 'Hey!',
    welcomeSubtitle: "Come join us: we'll help you find and create the best plans in your city!!!",
    downloadNow: 'Download Now!',
    allRightsReserved: 'All rights reserved.',
    // Group Chat
    votingOpen: 'Voting open! Tap to vote',
    awaitingAdminDecision: '⏳ Waiting for the admin to renew or close the plan',
    renewPlan: 'Renew',
    terminatePlan: 'Close',
    beFirstToMessage: "Start the convo! Don't be shy",
    chatLocked: 'Chat locked — waiting for admin decision',
    messagePlaceholder: 'Message...',
    // Admin actions
    adminActions: 'Admin Actions',
    editPlan: 'Edit Plan',
    editPlanUnavailableVoting: 'Unavailable during voting',
    editPlanUnavailableEnded: 'Unavailable while the plan is closed',
    // Voting modal
    howWasPlan: 'How was the plan?',
    yourOpinionHelps: 'Your opinion helps improve future events',
    votingClosesIn: 'Voting closes 6 hours after the plan ends',
    wantToLeavePlan: 'Want to leave this plan?',
    youVotedBad: "You voted that you didn't enjoy the plan",
    yesLeavePlan: 'Yes, leave the plan',
    noStayInGroup: 'No, stay in the group',
    // Renew plan modal
    adminActionsTitle: 'Admin Actions',
    chooseWhatToDo: 'Choose what to do with this plan',
    renewPlanBtn: '🔄 Renew Plan',
    terminatePlanBtn: '❌ Terminate Plan',
    cancel: 'Cancel',
    terminatePlanTitle: 'Terminate Plan ❌',
    terminatePlanDesc: 'The plan will be marked as terminated and stay visible for 24 hours before being automatically deleted.',
    terminateWarning: "⚠️ This can't be undone. All members will see that the plan was terminated.",
    back: 'Back',
    confirmTermination: 'Confirm Termination',
    renewPlanTitle: 'Renew Plan 🔄',
    renewPlanDesc: 'Everything will be renewed with a new date and time. Previous stories will be kept.',
    newDate: 'New Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    newAddress: 'New Address',
    fullAddress: 'Full address',
    confirmRenewal: 'Confirm Renewal',
    // Delete plan modal
    terminatePlanQuestion: 'Close Plan?',
    terminatePlanVisibleDesc: 'The plan will be marked as Closed and visible to all members for 24 hours, then automatically removed.',
    terminatePlanConfirm: 'Close Plan',
    // Plan renewed chat message
    planRenewed: "🔄 The plan has been renewed! Let's gooo 😎",
    planTerminatedMsg: '❌ The admin has closed this plan. The group will be removed in 24 hours.',
    // Settings - Appearance & Privacy
    appearance: 'Appearance',
    switchToLight: 'Switch to light theme',
    switchToDark: 'Switch to dark theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    privateProfile: 'Private Profile',
    publicProfile: 'Public Profile',
    privateProfileDesc: 'Only friends can see your stories, plans and friends',
    publicProfileDesc: 'Everyone can see your full profile',
    // GroupChat
    joinPlanToAccess: 'Join the plan to access the group and chat.',
    backBtn: '← Back',
    planUpdated: '✏️ Plan updated',
    terminatedBanner: '❌ Terminated',
    live: '🔵 Live',
    add: 'Add',
    you: 'You',
    user: 'User',
    members: 'Members',
    viewGroup: 'View Group →',
    pinned: '📌 Pinned',
    notPinned: 'Not Pinned',
    noStoriesToPin: 'No Stories to Pin',
    noMessagesToPin: 'No Messages to Pin',
    inviteFriends: 'Invite Friends',
    noFriendsToInvite: 'No Friends to Invite',
    sent: 'Sent',
    invite: 'Invite',
    admin: 'Admin',
    gallery: '📸 Gallery',
    noSharedMemories: 'No Shared Memories Yet',
    downloading: 'Downloading...',
    download: 'Download',
    noStickersYet: "No stickers yet. Add your first one!",
    searchAddress: 'Search address...',
    setCity: 'Set City',
    kmradius: 'km radius',
    chooseCityDescription: 'Choose a city to see plans near you',
    chooseYourCity: 'or choose your city',
    searchCity: '🔍 Search city...',
    select: 'Select...',
    member: 'Member',
    aboutCommunity: 'About this Community',
    active: 'Active',
    adminsCreatePlans: 'Admins create plans',
    plansApproval: 'Plans require approval',
    anyoneCreatePlans: 'Anyone can create plans',
    someone: 'Someone',
    joinedAsAdmin: 'joined as Admin',
    joinedCommunity: 'joined the community',
    newPlan: 'New plan',
    planCreated: 'plan created',
    postedStory: 'posted a story',
    communityStats: 'Community Stats',
    newMembersWeek: 'New Members\nthis week',
    storiesWeek: 'Stories\nthis week',
    upcomingPlans: 'Upcoming\nPlans',
    totalMembers: 'Total Members',
    joinedLast30d: 'Joined last 30d',
    liveActivity: 'Live Activity',
    noActivityYet: 'No activity yet',
    noActivityDesc: 'Activity will appear here as members join and participate',
    challengeNight: '🌙 Night Challenge',
    challengeDay: '☀️ Day Challenge',
    challengeWeekend: '🎉 Weekend Challenge',
    challengeCustom: '⚡ Challenge',
    challengeTimeLeft: 'left',
    challengeEnded: 'Challenge ended',
    challengeTapToParticipate: '📸 Tap to see & participate →',
    storiesSubmitted: 'stories submitted',
    challengeWinner: 'Winner',
    challengePostToParticipate: '📸 Post Your Story to Participate',
    challengeFinalLeaderboard: '🏅 Final Leaderboard',
    challengeLiveLeaderboard: '📊 Live Leaderboard',
    storySingular: 'story',
    storiesPlural: 'stories',
    views: 'views',
    challengePickWinner: 'Pick Winner',
    challengeBeFirst: 'Be the first to participate!',
    createChallenge: 'Create Challenge',
    createChallengeSubtitle: 'Announce a story challenge to the community',
    challengePickEmoji: 'Pick an emoji',
    challengeType: 'Type',
    challengeTypeNight: 'Night',
    challengeTypeNightDesc: 'Best night out story',
    challengeTypeDay: 'Day',
    challengeTypeDayDesc: 'Best daytime story',
    challengeTypeWeekend: 'Weekend',
    challengeTypeWeekendDesc: 'Weekend vibes',
    challengeTypeCustom: 'Custom',
    challengeTypeCustomDesc: 'Your own theme',
    challengeTitle: 'Title',
    challengeTitlePlaceholder: 'e.g. Best Sunset Shot Tonight 🌅',
    challengeDescription: 'Description',
    challengeDescriptionPlaceholder: 'Tell members what kind of stories you want to see...',
    challengeDuration: 'Duration',
    challengeDurationWeek: '1 week',
    challengePrize: 'Prize / Reward',
    challengePrizePlaceholder: 'e.g. Featured on the community page 🏆',
    challengeLinkPlan: 'Link to Plan',
    challengeNoSpecificPlan: 'No specific plan',
    challengeLaunch: 'Launch Challenge',
    challengeNewNotifTitle: 'New Challenge',
    challengeNewNotifMessage: 'A new challenge just launched! Post your story to participate.',
    optional: 'optional',
    editCommunity: 'Edit Community',
    communityName: 'Name',
    communityThemeColor: 'Theme Color',
    communityCoverImage: 'Cover Image',
    communityChangePhoto: 'Change photo',
    communityCoverPhoto: 'Cover photo',
    communityBackgroundImage: 'Background Image',
    communityBackgroundTexture: 'Background texture',
    communityVisibility: 'Visibility',
    communityPrivateDesc: 'Private — hidden from Home & Explore',
    communityPublicDesc: 'Public — visible to everyone',
    communityChatAccess: 'Chat Access',
    communityOpenToAll: 'Open to all',
    communityPlanPolicy: 'Plan Creation Policy',
    policyAnyone: 'Anyone',
    policyApproval: 'Needs Approval',
    policyAdminsOnly: 'Admins Only',
    deleteCommunity: 'Delete Community',
    leave: 'Leave',
    reportCommunity: 'Report Community',
    join: 'Join 🚀',
    membersCount: 'members',
    topMembers: 'Top Members',
    total: 'total',
    guideStep1Title: 'Welcome to the Community!',
    guideStep1Desc: "You're now part of this community. Here's a quick guide to get started.",
    guideStep2Title: 'Join & Create Plans',
    guideStep2Desc: 'Browse upcoming plans in the Plans tab. Join events or create your own!',
    guideStep3Title: 'Share Stories',
    guideStep3Desc: 'After attending a plan, post stories to share the vibe with the community.',
    guideStep4Title: 'Meet the Members',
    guideStep4Desc: "Check the Members tab to see who's active and discover top contributors.",
    guideNext: 'Next',
    guideLetsGo: "Let's go! 🚀",
    guideBack: 'Back',
    eventStories: 'Event Stories',
    moreStories: 'more stories',
    leaveCommunityTitle: 'Leave the Community?',
    leaveCommunityConfirm: 'Are you sure you want to leave',
    sortBy: 'Sort by',
    startTime: 'Start time',
    radius: 'Radius',
    partyType: 'Party type',
    search: 'Search...',
    clearFilters: 'Clear all filters',
    showMe: 'Show me',
    ageRange: 'Age range',
    city: 'City',
    searchCityPlaceholder: 'Search by city...',
    vybtPlusCity: 'Explore users from any city with Vybt Plus',
    similarVibes: 'Similar vibes',

  },

  es: {
    name: 'Español',
    flag: '🇪🇸',
    // Onboarding
    continue: 'Continuar',
    whereAreYou: '¿Dónde estás? 📍',
    locationSubtitle: 'Te mostraremos planes y gente cerca de ti.',
    useMyLocation: 'Usar mi ubicación actual',
    detecting: 'Detectando...',
    tapToDetect: 'Toca para detectar automáticamente',
    locationSetTo: 'Ubicación definida en',
    chooseLanguage: 'Elige tu idioma 🌍',
    languageSubtitle: 'Selecciona el idioma que quieres usar.',
    whatsYourName: '¿Cómo te llamas? 👋',
    nameSubtitle: 'Así es como otros usuarios te verán en Vybt.',
    yourNamePlaceholder: 'Tu nombre...',
    whatsYourGender: '¿Cuál es tu género?',
    genderSubtitle: 'Ayúdanos a personalizar tu experiencia',
    female: 'Femenino',
    male: 'Masculino',
    other: 'Otro',
    whatsYourBirthday: '¿Cuál es tu fecha de nacimiento?',
    birthdaySubtitle: 'Necesitas tener 16+ años para entrar en Vybt',
    ageVerified: '✓ Edad verificada',
    yearsOld: 'años',
    mustBe16: 'Necesitas tener al menos 16 años para usar Vybt',
    addYourPhotos: 'Añade tus fotos',
    photosSubtitle: 'Necesitas al menos 1 foto (primera foto para verificación)',
    mainPhoto: 'Principal (Obligatoria)',
    photo: 'Foto',
    photoVerificationWarning: 'Tu primera foto se usará para verificar tu perfil. Asegúrate de que tu cara esté 100% visible.',
    whatsYourVibe: '¿Cuál es tu vibe?',
    vibeSubtitle: 'Selecciona {min}–{max} estilos musicales que te molan',
    searchVibes: 'Busca las diferentes vibes...',
    vibesCount: 'vibes',
    selected: 'seleccionado',
    limitReached: 'Límite alcanzado — quita uno para elegir otro',
    whatPartiesDoYouLove: '¿Cuál es tu tipo de fiesta?',
    partySubtitle: 'Selecciona {min}–{max} tipos de fiestas',
    searchPartyTypes: 'Buscar tipos de fiestas...',
    typesCount: 'tipos',
    // Welcome complete
    welcomeTitle: '¡Bienvenido!',
    accountReady: 'Tu cuenta está lista',
    searchPlansTonight: '¿Buscar planes para esta noche?',
    explorePlansLocation: 'Explorar todos los planes en tu zona',
    letsGo: '¡Vamos! 🎉',
    // Verification step
    verifyYourProfile: 'Verifica tu perfil',
    verifyDesc1: 'Hazte un selfie para conseguir tu ',
    verifyBadge: 'sello azul de verificación',
    verifyDesc2: ' y generar confianza con otros usuarios.',
    verifyNow: 'Verificar Ahora',
    skipForNow: 'Lo hago Después',
    // Navigation
    home: 'Inicio',
    explore: 'Explorar',
    create: 'Crear',
    messages: 'Mensajes',
    profile: 'Perfil',
    // BottomNav menu
    addStory: 'Añadir Story',
    createNewPlan: 'Crear nuevo Plan',
    // Home
    myPlans: 'Mis Planes',
    seeAll: 'Ver todo',
    tonight: 'Esta Noche',
    forYou: 'Para Ti',
    happeningNow: 'Pasando Ahora',
    // Profile
    myFriends: 'Mis Amigos',
    joinedPartyPlans: 'Planes en los que estuve',
    myExperienceStories: 'Mis Stories',
    profileVerified: 'Perfil Verificado ✓',
    verifyProfile: 'Verificar Mi Perfil',
    friends: 'Amigos',
    stories: 'Stories',
    // Edit Profile
    editProfile: 'Editar Perfil',
    photos: 'Fotos (máximo 5) — la primera es tu foto de perfil.',
    displayName: 'Nombre de usuario',
    bio: 'Bio',
    bioPlaceholder: 'Cuéntanos más sobre ti...',
    dateOfBirth: 'Fecha de Nacimiento',
    yourLocation: 'Tu Ubicación',
    detectingLocation: 'Detectando tu ubicación...',
    tapToUseLocation: 'Toca para usar la ubicación actual',
    searchRadius: 'Radio de Búsqueda',
    yourVibes: 'Tus Vibes (máx. 5)',
    preferredPartyTypes: 'Tipos de Fiestas Preferidas',
    saveChanges: 'Guardar Cambios',
    // Settings
    settings: 'Ajustes',
    account: 'Cuenta',
    notifications: 'Notificaciones',
    manageAlerts: 'Gestiona tus alertas',
    language: 'Idioma',
    legalCommunity: 'Términos Legales & Comunidad',
    communityGuidelines: 'Normas de la Comunidad',
    termsConditions: 'Términos y Condiciones',
    privacyPolicy: 'Política de Privacidad',
    support: 'Soporte',
    helpFaq: 'Ayuda & FAQ',
    session: 'Sesión',
    logOut: 'Cerrar Sesión',
    deleteAccount: 'Eliminar Cuenta',
    deleteAccountSub: 'Eliminar permanentemente tus datos',
    chooseLanguageTitle: 'Elegir Idioma',
    administration: 'Administración',
    moderationPanel: 'Panel de Moderación',
    moderationSub: 'Revisar denuncias de contenido',
    // Explore
    plans: 'Planes',
    groups: 'Grupos',
    people: 'Personas',
    searchPlans: 'Buscar planes...',
    searchGroups: 'Buscar grupos...',
    searchPeople: 'Buscar personas...',
    filterPlans: 'Filtrar Planes',
    filterPeople: 'Filtrar Personas',
    allTag: 'Todos',
    onFire: 'En Llamas',
    mostMembers: 'Más Miembros',
    matchesVibes: 'Coincide con Mis Vibes',
    noPlansFound: 'No se encontraron planes',
    noUsersFound: 'No se encontraron usuarios',
    // Friends
    requests: 'Solicitudes',
    noFriendsYet: 'Sin amigos aún',
    noPendingRequests: 'Sin solicitudes pendientes',
    wantsToBeYourFriend: 'Quiere ser tu amigo',
    noLocation: 'Sin ubicación',
    // Notifications
    markAllRead: 'Marcar todas',
    removed: 'Eliminado',
    confirm: 'Confirmar',
    delete: 'Borrar',
    friendRequest: ' te envió una solicitud de amistad.',
    // MyStories
    noStoriesYet: 'Aún no has compartido ningún story',
    addFirstStory: 'Añade Tu Primer Story',
    unknownPlan: 'Plan Desconocido',
    // Plan Details
    going: 'Voy',
    groupChat: 'Chat del Grupo',
    joinPlan: 'Unirse al Plan',
    leavePlan: 'Salir',
    about: 'Info',
    experienceStories: 'Momentos',
    shareYourExperience: 'Comparte una experiencia increíble',
    storiesUnavailableVoting: 'Stories no disponibles durante la votación',
    planLimitWarning: 'Alcanzaste el límite de 3 planes en',
    leaveToJoin: 'Sal de un plan para unirte a este.',
    votingActiveNotice: '🗳️ Período de votación activo — No puedes unirte ni salir durante la votación (6 horas)',
    planTerminated: '❌ Plan Terminado',
    planTerminatedDesc: 'Este plan fue terminado por el admin y se eliminará en 24 horas',
    highlightPlan: 'Destacar este plan - €2.99',
    // Story visibility
    friendsVisibility: 'Amigos',
    groupOnly: 'Grupo',
    // Welcome page
    welcomeHero: '¡Hola!',
    welcomeSubtitle: 'Únete a nosotros: te ayudaremos a encontrar y crear los mejores planes en tu ciudad!!!',
    downloadNow: '¡Descárgalo Ahora!',
    allRightsReserved: 'Todos los derechos reservados.',
    // Group Chat
    votingOpen: '¡Votación abierta! Toca para votar',
    awaitingAdminDecision: '⏳ Esperando que el admin renueve o cierre el plan',
    renewPlan: 'Renovar',
    terminatePlan: 'Cerrar',
    beFirstToMessage: '¡Empieza la conv! No te cortes',
    chatLocked: 'Chat bloqueado — esperando decisión del admin',
    messagePlaceholder: 'Mensaje...',
    // Admin actions
    adminActions: 'Acciones Admin',
    editPlan: 'Editar Plan',
    editPlanUnavailableVoting: 'No disponible durante la votación',
    editPlanUnavailableEnded: 'No disponible mientras el plan está cerrado',
    // Voting modal
    howWasPlan: '¿Cómo estuvo el plan?',
    yourOpinionHelps: 'Tu opinión ayuda a mejorar futuros eventos',
    votingClosesIn: 'La votación cierra 6 horas después del fin del plan',
    wantToLeavePlan: '¿Quieres salir de este plan?',
    youVotedBad: 'Votaste que no te gustó el plan',
    yesLeavePlan: 'Sí, salir del plan',
    noStayInGroup: 'No, quedarme en el grupo',
    // Renew plan modal
    adminActionsTitle: 'Acciones del Admin',
    chooseWhatToDo: 'Elige qué hacer con este plan',
    renewPlanBtn: '🔄 Renovar Plan',
    terminatePlanBtn: '❌ Terminar Plan',
    cancel: 'Cancelar',
    terminatePlanTitle: 'Terminar Plan ❌',
    terminatePlanDesc: 'El plan se marcará como terminado y permanecerá visible 24 horas antes de eliminarse automáticamente.',
    terminateWarning: '⚠️ Esto no se puede deshacer. Todos los miembros verán que el plan fue terminado.',
    back: 'Volver',
    confirmTermination: 'Confirmar Terminación',
    renewPlanTitle: 'Renovar Plan 🔄',
    renewPlanDesc: 'Todo se renovará con nueva fecha y hora. Los stories anteriores se mantendrán.',
    newDate: 'Nueva Fecha',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Fin',
    newAddress: 'Nueva Dirección',
    fullAddress: 'Dirección completa',
    confirmRenewal: 'Confirmar Renovación',
    // Delete plan modal
    terminatePlanQuestion: '¿Cerrar Plan?',
    terminatePlanVisibleDesc: 'El plan se marcará como Cerrado y visible para todos los miembros durante 24 horas, luego se eliminará automáticamente.',
    terminatePlanConfirm: 'Cerrar Plan',
    // Plan renewed chat message
    planRenewed: "🔄 ¡El plan ha sido renovado! Let's gooo 😎",
    planTerminatedMsg: '❌ El admin ha cerrado este plan. El grupo se eliminará en 24 horas.',
    // Settings - Appearance & Privacy
    appearance: 'Apariencia',
    switchToLight: 'Cambiar a tema claro',
    switchToDark: 'Cambiar a tema oscuro',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    privateProfile: 'Perfil Privado',
    publicProfile: 'Perfil Público',
    privateProfileDesc: 'Solo tus amigos ven tus stories, planes y amigos',
    publicProfileDesc: 'Todo el mundo puede ver tu perfil completo',
    // GroupChat
    joinPlanToAccess: 'Únete al plan para acceder al grupo y chatear.',
    backBtn: '← Volver',
    planUpdated: '✏️ Plan actualizado',
    terminatedBanner: '❌ Terminado',
    live: '🔵 En Vivo',
    add: 'Añadir',
    you: 'Tú',
    user: 'Usuario',
    members: 'Miembros',
    viewGroup: 'Ver Grupo →',
    pinned: '📌 Fijado',
    notPinned: 'No Fijado',
    noStoriesToPin: 'Sin Stories para Fijar',
    noMessagesToPin: 'Sin Mensajes para Fijar',
    inviteFriends: 'Invitar Amigos',
    noFriendsToInvite: 'Sin Amigos para Invitar',
    sent: 'Enviado',
    invite: 'Invitar',
    admin: 'Administrador',
    gallery: '📸 Galería',
    noSharedMemories: 'Ningún Recuerdo Compartido Aún',
    downloading: 'Descargando...',
    download: 'Descargar',
    noStickersYet: "Aún no hay stickers. ¡Agrega el primero!",
    searchAddress: 'Buscar dirección...',
    setCity: 'Definir ciudad',
    kmradius: 'km radio',
    chooseCityDescription: 'Elige una ciudad para ver planes cerca de ti',
    chooseYourCity: 'o elige tu ciudad',
    searchCity: '🔍 Buscar ciudad...',
    select: 'Seleccionar...',
    member: 'Miembro',
    aboutCommunity: 'Acerca de esta Comunidad',
    active: 'Activo',
    adminsCreatePlans: 'Los administradores crean planes',
    plansApproval: 'Los planes requieren aprobación',
    anyoneCreatePlans: 'Cualquiera puede crear planes',
    someone: 'Alguien',
    joinedAsAdmin: 'se unió como Admin',
    joinedCommunity: 'se unió a la comunidad',
    newPlan: 'Nuevo plan',
    planCreated: 'plan creado',
    postedStory: 'publicó un story',
    communityStats: 'Estadísticas de la Comunidad',
    newMembersWeek: 'Nuevos Miembros\nesta semana',
    storiesWeek: 'Stories\nesta semana',
    upcomingPlans: 'Planes\nPróximos',
    totalMembers: 'Total de Miembros',
    joinedLast30d: 'Unido en los últimos 30d',
    liveActivity: 'Actividad en Vivo',
    noActivityYet: 'Sin actividad aún',
    noActivityDesc: 'La actividad aparecerá aquí a medida que los miembros se unan y participen',
    challengeNight: '🌙 Reto Nocturno',
    challengeDay: '☀️ Reto Diurno',
    challengeWeekend: '🎉 Reto de Fin de Semana',
    challengeCustom: '⚡ Reto',
    challengeTimeLeft: 'restantes',
    challengeEnded: 'Reto finalizado',
    challengeTapToParticipate: '📸 Toca para ver y participar →',
    storiesSubmitted: 'stories enviados',
    challengeWinner: 'Ganador',
    challengePostToParticipate: '📸 Publica tu Story para participar',
    challengeFinalLeaderboard: '🏅 Clasificación Final',
    challengeLiveLeaderboard: '📊 Clasificación en Vivo',
    storySingular: 'story',
    storiesPlural: 'stories',
    views: 'visualizaciones',
    challengePickWinner: 'Elegir Ganador',
    challengeBeFirst: '¡Sé el primero en participar!',
    createChallenge: 'Crear Reto',
    createChallengeSubtitle: 'Anuncia un reto de stories a la comunidad',
    challengePickEmoji: 'Elige un emoji',
    challengeType: 'Tipo',
    challengeTypeNight: 'Noche',
    challengeTypeNightDesc: 'Mejor story de noche',
    challengeTypeDay: 'Día',
    challengeTypeDayDesc: 'Mejor story del día',
    challengeTypeWeekend: 'Fin de Semana',
    challengeTypeWeekendDesc: 'Vibe de fin de semana',
    challengeTypeCustom: 'Personalizado',
    challengeTypeCustomDesc: 'Tu propio tema',
    challengeTitle: 'Título',
    challengeTitlePlaceholder: 'ej: Mejor foto del atardecer esta noche 🌅',
    challengeDescription: 'Descripción',
    challengeDescriptionPlaceholder: 'Cuéntale a la gente qué tipo de stories quieres ver...',
    challengeDuration: 'Duración',
    challengeDurationWeek: '1 semana',
    challengePrize: 'Premio / Recompensa',
    challengePrizePlaceholder: 'ej: Destacado en la página de la comunidad 🏆',
    challengeLinkPlan: 'Vincular a un Plan',
    challengeNoSpecificPlan: 'Ningún plan específico',
    challengeLaunch: 'Lanzar Reto',
    challengeNewNotifTitle: 'Nuevo Reto',
    challengeNewNotifMessage: '¡Se lanzó un nuevo reto! Publica tu story para participar.',
    optional: 'opcional',
    editCommunity: 'Editar Comunidad',
    communityName: 'Nombre',
    communityThemeColor: 'Color del Tema',
    communityCoverImage: 'Foto de Portada',
    communityChangePhoto: 'Cambiar foto',
    communityCoverPhoto: 'Foto de portada',
    communityBackgroundImage: 'Imagen de Fondo',
    communityBackgroundTexture: 'Textura de fondo',
    communityVisibility: 'Visibilidad',
    communityPrivateDesc: 'Privada — oculta del Inicio y Explorar',
    communityPublicDesc: 'Pública — visible para todos',
    communityChatAccess: 'Acceso al Chat',
    communityOpenToAll: 'Abierto a todos',
    communityPlanPolicy: 'Política de Creación de Planes',
    policyAnyone: 'Cualquiera',
    policyApproval: 'Necesita Aprobación',
    policyAdminsOnly: 'Solo Admins',
    deleteCommunity: 'Eliminar Comunidad',
    leave: 'Salir',
    reportCommunity: 'Denunciar Comunidad',
    join: 'Unirse 🚀',
    membersCount: 'miembros',
    topMembers: 'Top Miembros',
    total: 'total',
    guideStep1Title: '¡Bienvenido a la Comunidad!',
    guideStep1Desc: 'Ya eres parte de esta comunidad. Aquí tienes una guía rápida para empezar.',
    guideStep2Title: 'Únete y Crea Planes',
    guideStep2Desc: 'Explora los planes en la pestaña Planes. ¡Únete a eventos o crea el tuyo!',
    guideStep3Title: 'Comparte Stories',
    guideStep3Desc: 'Después de ir a un plan, publica stories para mostrar el ambiente a la comunidad.',
    guideStep4Title: 'Conoce a los Miembros',
    guideStep4Desc: 'Ve a la pestaña Miembros para ver quién está activo y descubrir los tops.',
    guideNext: 'Siguiente',
    guideLetsGo: '¡Vamos! 🚀',
    guideBack: 'Volver',
    eventStories: 'Stories del Evento',
    moreStories: 'más stories',
    leaveCommunityTitle: '¿Salir de la Comunidad?',
    leaveCommunityConfirm: '¿Seguro que quieres salir de',
    sortBy: 'Ordenar por',
    startTime: 'Hora de inicio',
    radius: 'Radio',
    partyType: 'Tipo de fiesta',
    search: 'Buscar...',
    clearFilters: 'Limpiar filtros',
    showMe: 'Mostrar',
    ageRange: 'Rango de edad',
    city: 'Ciudad',
    searchCityPlaceholder: 'Buscar por ciudad...',
    vybtPlusCity: 'Explora usuarios de cualquier ciudad con Vybt Plus',
    similarVibes: 'Vibes similares',


  },

  fr: {
    name: 'Français',
    flag: '🇫🇷',
    // Onboarding
    continue: 'Continuer',
    whereAreYou: 'T\'es où ? 📍',
    locationSubtitle: 'On te montrera des plans et des gens près de toi.',
    useMyLocation: 'Utiliser ma position actuelle',
    detecting: 'Détection...',
    tapToDetect: 'Appuie pour détecter automatiquement',
    locationSetTo: 'Position définie sur',
    chooseLanguage: 'Choisis ta langue 🌍',
    languageSubtitle: 'Sélectionne la langue que tu veux utiliser.',
    whatsYourName: 'Tu t\'appelles comment ? 👋',
    nameSubtitle: 'C\'est comme ça que les autres te verront sur Vybt.',
    yourNamePlaceholder: 'Ton prénom...',
    whatsYourGender: 'T\'as quel genre ?',
    genderSubtitle: 'Aide-nous à personnaliser ton expérience',
    female: 'Féminin',
    male: 'Masculin',
    other: 'Autre',
    whatsYourBirthday: 'C\'est quoi ta date de naissance ?',
    birthdaySubtitle: 'Tu dois avoir 16+ ans pour rejoindre Vybt',
    ageVerified: '✓ Âge vérifié',
    yearsOld: 'ans',
    mustBe16: 'Tu dois avoir au moins 16 ans pour utiliser Vybt',
    addYourPhotos: 'Ajoute tes photos',
    photosSubtitle: 'Au moins 1 photo est requise (première photo pour vérification)',
    mainPhoto: 'Principale (Obligatoire)',
    photo: 'Photo',
    photoVerificationWarning: 'Ta première photo sera utilisée pour vérifier ton profil. Assure-toi que ton visage est 100% visible.',
    whatsYourVibe: 'C\'est quoi ton vibe ?',
    vibeSubtitle: 'Sélectionne {min}–{max} styles musicaux qui te correspondent',
    searchVibes: 'Cherche les différentes vibes...',
    vibesCount: 'vibes',
    selected: 'sélectionné',
    limitReached: 'Limite atteinte — enlève-en un pour en choisir un autre',
    whatPartiesDoYouLove: 'C\'est quoi ton type de soirée ?',
    partySubtitle: 'Sélectionne {min}–{max} types de soirées',
    searchPartyTypes: 'Chercher des types de soirées...',
    typesCount: 'types',
    // Welcome complete
    welcomeTitle: 'Bienvenue !',
    accountReady: 'Ton compte est prêt',
    searchPlansTonight: 'Chercher des plans pour ce soir ?',
    explorePlansLocation: 'Explorer tous les plans dans ta zone',
    letsGo: 'C\'est parti ! 🎉',
    // Verification step
    verifyYourProfile: 'Vérifie ton profil',
    verifyDesc1: 'Prends un selfie pour obtenir ton ',
    verifyBadge: 'badge bleu de vérification',
    verifyDesc2: ' et gagner la confiance des autres utilisateurs.',
    verifyNow: 'Vérifier Maintenant',
    skipForNow: 'Je le fais Plus Tard',
    // Navigation
    home: 'Accueil',
    explore: 'Explorer',
    create: 'Créer',
    messages: 'Messages',
    profile: 'Profil',
    // BottomNav menu
    addStory: 'Ajouter un Story',
    createNewPlan: 'Créer un nouveau Plan',
    // Home
    myPlans: 'Mes Plans',
    seeAll: 'Voir tout',
    tonight: 'Ce Soir',
    forYou: 'Pour Toi',
    happeningNow: 'En ce Moment',
    // Profile
    myFriends: 'Mes Amis',
    joinedPartyPlans: 'Plans auxquels j\'ai participé',
    myExperienceStories: 'Mes Stories',
    profileVerified: 'Profil Vérifié ✓',
    verifyProfile: 'Vérifier Mon Profil',
    friends: 'Amis',
    stories: 'Stories',
    // Edit Profile
    editProfile: 'Modifier le Profil',
    photos: 'Photos (max 5) — la première est ta photo de profil.',
    displayName: 'Nom d\'affichage',
    bio: 'Bio',
    bioPlaceholder: 'Parle-nous un peu de toi...',
    dateOfBirth: 'Date de Naissance',
    yourLocation: 'Ta Localisation',
    detectingLocation: 'Détection de ta position...',
    tapToUseLocation: 'Appuie pour utiliser la position actuelle',
    searchRadius: 'Rayon de Recherche',
    yourVibes: 'Tes Vibes (max 5)',
    preferredPartyTypes: 'Types de Soirées Préférés',
    saveChanges: 'Enregistrer',
    // Settings
    settings: 'Paramètres',
    account: 'Compte',
    notifications: 'Notifications',
    manageAlerts: 'Gère tes alertes',
    language: 'Langue',
    legalCommunity: 'Mentions Légales & Communauté',
    communityGuidelines: 'Règles de la Communauté',
    termsConditions: 'Conditions d\'Utilisation',
    privacyPolicy: 'Politique de Confidentialité',
    support: 'Support',
    helpFaq: 'Aide & FAQ',
    session: 'Session',
    logOut: 'Se Déconnecter',
    deleteAccount: 'Supprimer le Compte',
    deleteAccountSub: 'Supprimer définitivement tes données',
    chooseLanguageTitle: 'Choisir la Langue',
    administration: 'Administration',
    moderationPanel: 'Panneau de Modération',
    moderationSub: 'Examiner les signalements de contenu',
    // Explore
    plans: 'Plans',
    groups: 'Groupes',
    people: 'Personnes',
    searchPlans: 'Chercher des plans...',
    searchGroups: 'Chercher des groupes...',
    searchPeople: 'Chercher des personnes...',
    filterPlans: 'Filtrer les Plans',
    filterPeople: 'Filtrer les Personnes',
    allTag: 'Tous',
    onFire: 'En Feu',
    mostMembers: 'Plus de Membres',
    matchesVibes: 'Correspond à Mes Vibes',
    noPlansFound: 'Aucun plan trouvé',
    noUsersFound: 'Aucun utilisateur trouvé',
    // Friends
    requests: 'Demandes',
    noFriendsYet: 'Pas encore d\'amis',
    noPendingRequests: 'Pas de demandes en attente',
    wantsToBeYourFriend: 'Veut être ton ami',
    noLocation: 'Pas de localisation',
    // Notifications
    markAllRead: 'Tout marquer',
    removed: 'Supprimé',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    friendRequest: ' t\'a envoyé une demande d\'ami.',
    // MyStories
    noStoriesYet: 'T\'as pas encore partagé de story',
    addFirstStory: 'Ajoute Ton Premier Story',
    unknownPlan: 'Plan Inconnu',
    // Plan Details
    going: 'J\'y vais',
    groupChat: 'Chat du Groupe',
    joinPlan: 'Rejoindre le Plan',
    leavePlan: 'Quitter',
    about: 'Infos',
    experienceStories: 'Moments',
    shareYourExperience: 'Partage une expérience incroyable',
    storiesUnavailableVoting: 'Stories indisponibles pendant le vote',
    planLimitWarning: 'T\'as atteint la limite de 3 plans à',
    leaveToJoin: 'Quitte un plan pour rejoindre celui-ci.',
    votingActiveNotice: '🗳️ Période de vote active — Tu peux pas rejoindre ou quitter pendant le vote (6 heures)',
    planTerminated: '❌ Plan Terminé',
    planTerminatedDesc: 'Ce plan a été terminé par l\'admin et sera supprimé dans 24 heures',
    highlightPlan: 'Mettre ce plan en avant - €2.99',
    // Story visibility
    friendsVisibility: 'Amis',
    groupOnly: 'Groupe',
    // Welcome page
    welcomeHero: 'Salut !',
    welcomeSubtitle: 'Rejoins-nous : on t\'aide à trouver et créer les meilleurs plans dans ta ville !!!',
    downloadNow: 'Télécharge Maintenant !',
    allRightsReserved: 'Tous droits réservés.',
    // Group Chat
    votingOpen: 'Vote ouvert ! Appuie pour voter',
    awaitingAdminDecision: '⏳ En attente que l\'admin renouvelle ou ferme le plan',
    renewPlan: 'Renouveler',
    terminatePlan: 'Fermer',
    beFirstToMessage: 'Lance la conv ! Vas-y sans hésiter',
    chatLocked: 'Chat verrouillé — en attente de la décision de l\'admin',
    messagePlaceholder: 'Message...',
    // Admin actions
    adminActions: 'Actions Admin',
    editPlan: 'Modifier le Plan',
    editPlanUnavailableVoting: 'Indisponible pendant le vote',
    editPlanUnavailableEnded: 'Indisponible pendant que le plan est fermé',
    // Voting modal
    howWasPlan: 'C\'était comment le plan ?',
    yourOpinionHelps: 'Ton avis aide à améliorer les futurs events',
    votingClosesIn: 'Le vote ferme 6 heures après la fin du plan',
    wantToLeavePlan: 'Tu veux quitter ce plan ?',
    youVotedBad: 'T\'as voté que le plan t\'a pas plu',
    yesLeavePlan: 'Oui, quitter le plan',
    noStayInGroup: 'Non, rester dans le groupe',
    // Renew plan modal
    adminActionsTitle: 'Actions de l\'Admin',
    chooseWhatToDo: 'Choisis quoi faire avec ce plan',
    renewPlanBtn: '🔄 Renouveler le Plan',
    terminatePlanBtn: '❌ Terminer le Plan',
    cancel: 'Annuler',
    terminatePlanTitle: 'Terminer le Plan ❌',
    terminatePlanDesc: 'Le plan sera marqué comme terminé et restera visible 24 heures avant d\'être supprimé automatiquement.',
    terminateWarning: '⚠️ C\'est irréversible. Tous les membres verront que le plan a été terminé.',
    back: 'Retour',
    confirmTermination: 'Confirmer la Fin',
    renewPlanTitle: 'Renouveler le Plan 🔄',
    renewPlanDesc: 'Tout sera renouvelé avec une nouvelle date et heure. Les stories précédents seront conservés.',
    newDate: 'Nouvelle Date',
    startTime: 'Heure de Début',
    endTime: 'Heure de Fin',
    newAddress: 'Nouvelle Adresse',
    fullAddress: 'Adresse complète',
    confirmRenewal: 'Confirmer le Renouvellement',
    // Delete plan modal
    terminatePlanQuestion: 'Fermer le Plan ?',
    terminatePlanVisibleDesc: 'Le plan sera marqué comme Fermé et visible pour tous les membres pendant 24 heures, puis supprimé automatiquement.',
    terminatePlanConfirm: 'Fermer le Plan',
    // Plan renewed chat message
    planRenewed: "🔄 Le plan a été renouvelé ! Let's gooo 😎",
    planTerminatedMsg: '❌ L\'admin a fermé ce plan. Le groupe sera supprimé dans 24 heures.',
    // Settings - Appearance & Privacy
    appearance: 'Apparence',
    switchToLight: 'Passer au thème clair',
    switchToDark: 'Passer au thème sombre',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    privateProfile: 'Profil Privé',
    publicProfile: 'Profil Public',
    privateProfileDesc: 'Seuls tes amis voient tes stories, plans et amis',
    publicProfileDesc: 'Tout le monde peut voir ton profil complet',
    // GroupChat
    joinPlanToAccess: 'Rejoins le plan pour accéder au groupe et chatter.',
    backBtn: '← Retour',
    planUpdated: '✏️ Plan mis à jour',
    terminatedBanner: '❌ Terminé',
    live: '🔵 En Direct',
    add: 'Ajouter',
    you: 'Tu',
    user: 'Utilisateur',
    members: 'Membres',
    viewGroup: 'Voir le Groupe →',
    pinned: '📌 Épinglé',
    notPinned: 'Non Épinglé',
    noStoriesToPin: 'Aucune Story à Épingler',
    noMessagesToPin: 'Aucun Message à Épingler',
    inviteFriends: 'Inviter des Amis',
    noFriendsToInvite: 'Aucun Ami à Inviter',
    sent: 'Envoyé',
    invite: 'Inviter',
    admin: 'Administrateur',
    gallery: '📸 Galerie',
    noSharedMemories: 'Aucun Souvenir Partagé Pour l’Instant',
    downloading: 'Téléchargement...',
    download: 'Télécharger',
    noStickersYet: "Pas encore d'autocollants. Ajoutez le premier !",
    searchAddress: 'Rechercher une adresse...',
    setCity: 'Définir la ville',
    kmradius: 'rayon km',
    chooseCityDescription: 'Choisissez une ville pour voir des plans près de vous',
    chooseYourCity: 'ou choisissez votre ville',
    searchCity: '🔍 Rechercher une ville...',
    select: 'Sélectionner...',
    member: 'Membre',
    aboutCommunity: 'À propos de cette Communauté',
    active: 'Actif',
    adminsCreatePlans: 'Les admins créent des plans',
    plansApproval: 'Les plans nécessitent une approbation',
    anyoneCreatePlans: 'Tout le monde peut créer des plans',
    someone: 'Quelqu\'un',
    joinedAsAdmin: 'a rejoint en tant qu\'Admin',
    joinedCommunity: 'a rejoint la communauté',
    newPlan: 'Nouveau plan',
    planCreated: 'plan créé',
    postedStory: 'a posté un story',
    communityStats: 'Stats de la Communauté',
    newMembersWeek: 'Nouveaux Membres\ncette semaine',
    storiesWeek: 'Stories\ncette semaine',
    upcomingPlans: 'Plans\nà Venir',
    totalMembers: 'Total Membres',
    joinedLast30d: 'Rejoint ces 30 derniers jours',
    liveActivity: 'Activité en Direct',
    noActivityYet: 'Pas encore d\'activité',
    noActivityDesc: 'L\'activité apparaîtra ici au fur et à mesure que les membres rejoignent et participent',
    challengeNight: '🌙 Défi Nocturne',
    challengeDay: '☀️ Défi Journée',
    challengeWeekend: '🎉 Défi Week-end',
    challengeCustom: '⚡ Défi',
    challengeTimeLeft: 'restants',
    challengeEnded: 'Défi terminé',
    challengeTapToParticipate: '📸 Appuie pour voir et participer →',
    storiesSubmitted: 'stories soumis',
    challengeWinner: 'Gagnant',
    challengePostToParticipate: '📸 Poste ton Story pour participer',
    challengeFinalLeaderboard: '🏅 Classement Final',
    challengeLiveLeaderboard: '📊 Classement en Direct',
    storySingular: 'story',
    storiesPlural: 'stories',
    views: 'vues',
    challengePickWinner: 'Choisir le Gagnant',
    challengeBeFirst: 'Sois le premier à participer !',
    createChallenge: 'Créer un Défi',
    createChallengeSubtitle: 'Lance un défi de stories à la communauté',
    challengePickEmoji: 'Choisis un emoji',
    challengeType: 'Type',
    challengeTypeNight: 'Nuit',
    challengeTypeNightDesc: 'Meilleur story de soirée',
    challengeTypeDay: 'Journée',
    challengeTypeDayDesc: 'Meilleur story de la journée',
    challengeTypeWeekend: 'Week-end',
    challengeTypeWeekendDesc: 'Vibe de week-end',
    challengeTypeCustom: 'Personnalisé',
    challengeTypeCustomDesc: 'Ton propre thème',
    challengeTitle: 'Titre',
    challengeTitlePlaceholder: 'ex : Meilleure photo du coucher de soleil ce soir 🌅',
    challengeDescription: 'Description',
    challengeDescriptionPlaceholder: 'Dis aux membres quel type de stories tu veux voir...',
    challengeDuration: 'Durée',
    challengeDurationWeek: '1 semaine',
    challengePrize: 'Prix / Récompense',
    challengePrizePlaceholder: 'ex : Mis en avant sur la page de la communauté 🏆',
    challengeLinkPlan: 'Lier à un Plan',
    challengeNoSpecificPlan: 'Aucun plan spécifique',
    challengeLaunch: 'Lancer le Défi',
    challengeNewNotifTitle: 'Nouveau Défi',
    challengeNewNotifMessage: 'Un nouveau défi vient d\'être lancé ! Poste ton story pour participer.',
    optional: 'optionnel',
    editCommunity: 'Modifier la Communauté',
    communityName: 'Nom',
    communityThemeColor: 'Couleur du Thème',
    communityCoverImage: 'Photo de Couverture',
    communityChangePhoto: 'Changer la photo',
    communityCoverPhoto: 'Photo de couverture',
    communityBackgroundImage: 'Image de Fond',
    communityBackgroundTexture: 'Texture de fond',
    communityVisibility: 'Visibilité',
    communityPrivateDesc: 'Privée — cachée de l\'Accueil et Explorer',
    communityPublicDesc: 'Publique — visible par tout le monde',
    communityChatAccess: 'Accès au Chat',
    communityOpenToAll: 'Ouvert à tous',
    communityPlanPolicy: 'Politique de Création de Plans',
    policyAnyone: 'N\'importe qui',
    policyApproval: 'Approbation requise',
    policyAdminsOnly: 'Admins uniquement',
    deleteCommunity: 'Supprimer la Communauté',
    leave: 'Quitter',
    reportCommunity: 'Signaler la Communauté',
    join: 'Rejoindre 🚀',
    membersCount: 'membres',
    topMembers: 'Top Membres',
    total: 'total',
    guideStep1Title: 'Bienvenue dans la Communauté !',
    guideStep1Desc: 'Tu fais maintenant partie de cette communauté. Voici un guide rapide pour démarrer.',
    guideStep2Title: 'Rejoins et Crée des Plans',
    guideStep2Desc: "Parcours les plans dans l'onglet Plans. Rejoins des events ou crée le tien !",
    guideStep3Title: 'Partage des Stories',
    guideStep3Desc: "Après un plan, poste des stories pour partager l'ambiance avec la communauté.",
    guideStep4Title: 'Rencontre les Membres',
    guideStep4Desc: "Va dans l'onglet Membres pour voir qui est actif et découvrir les tops.",
    guideNext: 'Suivant',
    guideLetsGo: "C'est parti ! 🚀",
    guideBack: 'Retour',
    eventStories: 'Stories de l\'Événement',
    moreStories: 'stories de plus',
    leaveCommunityTitle: 'Quitter la Communauté ?',
    leaveCommunityConfirm: 'T\'es sûr de vouloir quitter',
    sortBy: 'Trier par',
    startTime: 'Heure de début',
    radius: 'Rayon',
    partyType: 'Type de soirée',
    search: 'Rechercher...',
    clearFilters: 'Effacer les filtres',
    showMe: 'Afficher',
    ageRange: 'Tranche d’âge',
    city: 'Ville',
    searchCityPlaceholder: 'Rechercher par ville...',
    vybtPlusCity: 'Explore des utilisateurs de n’importe quelle ville avec Vybt Plus',
    similarVibes: 'Vibes similaires',
  },

  it: {
    name: 'Italiano',
    flag: '🇮🇹',
    // Onboarding
    continue: 'Continua',
    whereAreYou: 'Dove sei? 📍',
    locationSubtitle: 'Ti mostreremo piani e persone vicino a te.',
    useMyLocation: 'Usa la mia posizione attuale',
    detecting: 'Rilevamento...',
    tapToDetect: 'Tocca per rilevare automaticamente',
    locationSetTo: 'Posizione impostata su',
    chooseLanguage: 'Scegli la tua lingua 🌍',
    languageSubtitle: 'Seleziona la lingua che vuoi usare.',
    whatsYourName: 'Come ti chiami? 👋',
    nameSubtitle: 'È così che gli altri ti vedranno su Vybt.',
    yourNamePlaceholder: 'Il tuo nome...',
    whatsYourGender: 'Qual è il tuo genere?',
    genderSubtitle: 'Aiutaci a personalizzare la tua esperienza',
    female: 'Femmina',
    male: 'Maschio',
    other: 'Altro',
    whatsYourBirthday: 'Qual è la tua data di nascita?',
    birthdaySubtitle: 'Devi avere 16+ anni per entrare in Vybt',
    ageVerified: '✓ Età verificata',
    yearsOld: 'anni',
    mustBe16: 'Devi avere almeno 16 anni per usare Vybt',
    addYourPhotos: 'Aggiungi le tue foto',
    photosSubtitle: 'Serve almeno 1 foto (prima foto per la verifica)',
    mainPhoto: 'Principale (Obbligatoria)',
    photo: 'Foto',
    photoVerificationWarning: 'La tua prima foto sarà usata per verificare il profilo. Assicurati che il tuo viso sia 100% visibile.',
    whatsYourVibe: 'Qual è il tuo vibe?',
    vibeSubtitle: 'Seleziona {min}–{max} stili musicali che ti piacciono',
    searchVibes: 'Cerca i diversi vibes...',
    vibesCount: 'vibes',
    selected: 'selezionato',
    limitReached: 'Limite raggiunto — rimuovine uno per sceglierne un altro',
    whatPartiesDoYouLove: 'Che tipo di festa ti piace?',
    partySubtitle: 'Seleziona {min}–{max} tipi di feste',
    searchPartyTypes: 'Cerca tipi di feste...',
    typesCount: 'tipi',
    // Welcome complete
    welcomeTitle: 'Benvenuto!',
    accountReady: 'Il tuo account è pronto',
    searchPlansTonight: 'Cercare piani per stasera?',
    explorePlansLocation: 'Esplora tutti i piani nella tua zona',
    letsGo: 'Andiamo! 🎉',
    // Verification step
    verifyYourProfile: 'Verifica il tuo profilo',
    verifyDesc1: 'Fatti un selfie per ottenere il tuo ',
    verifyBadge: 'badge blu di verifica',
    verifyDesc2: ' e guadagnare la fiducia degli altri utenti.',
    verifyNow: 'Verifica Ora',
    skipForNow: 'Lo faccio Dopo',
    // Navigation
    home: 'Home',
    explore: 'Esplora',
    create: 'Crea',
    messages: 'Messaggi',
    profile: 'Profilo',
    // BottomNav menu
    addStory: 'Aggiungi Story',
    createNewPlan: 'Crea nuovo Piano',
    // Home
    myPlans: 'I Miei Piani',
    seeAll: 'Vedi tutto',
    tonight: 'Stasera',
    forYou: 'Per Te',
    happeningNow: 'In Corso Ora',
    // Profile
    myFriends: 'I Miei Amici',
    joinedPartyPlans: 'Piani a cui ho partecipato',
    myExperienceStories: 'I Miei Stories',
    profileVerified: 'Profilo Verificato ✓',
    verifyProfile: 'Verifica Il Mio Profilo',
    friends: 'Amici',
    stories: 'Stories',
    // Edit Profile
    editProfile: 'Modifica Profilo',
    photos: 'Foto (max 5) — la prima è la tua foto profilo.',
    displayName: 'Nome visualizzato',
    bio: 'Bio',
    bioPlaceholder: 'Raccontaci qualcosa di te...',
    dateOfBirth: 'Data di Nascita',
    yourLocation: 'La Tua Posizione',
    detectingLocation: 'Rilevamento della tua posizione...',
    tapToUseLocation: 'Tocca per usare la posizione attuale',
    searchRadius: 'Raggio di Ricerca',
    yourVibes: 'I Tuoi Vibes (max 5)',
    preferredPartyTypes: 'Tipi di Feste Preferiti',
    saveChanges: 'Salva',
    // Settings
    settings: 'Impostazioni',
    account: 'Account',
    notifications: 'Notifiche',
    manageAlerts: 'Gestisci le tue notifiche',
    language: 'Lingua',
    legalCommunity: 'Termini Legali & Comunità',
    communityGuidelines: 'Regole della Comunità',
    termsConditions: 'Termini e Condizioni',
    privacyPolicy: 'Informativa sulla Privacy',
    support: 'Supporto',
    helpFaq: 'Aiuto & FAQ',
    session: 'Sessione',
    logOut: 'Esci',
    deleteAccount: 'Elimina Account',
    deleteAccountSub: 'Rimuovi definitivamente i tuoi dati',
    chooseLanguageTitle: 'Scegli la Lingua',
    administration: 'Amministrazione',
    moderationPanel: 'Pannello di Moderazione',
    moderationSub: 'Esamina le segnalazioni di contenuto',
    // Explore
    plans: 'Piani',
    groups: 'Gruppi',
    people: 'Persone',
    searchPlans: 'Cerca piani...',
    searchGroups: 'Cerca gruppi...',
    searchPeople: 'Cerca persone...',
    filterPlans: 'Filtra Piani',
    filterPeople: 'Filtra Persone',
    allTag: 'Tutti',
    onFire: 'Di Fuoco',
    mostMembers: 'Più Membri',
    matchesVibes: 'In linea con i Miei Vibes',
    noPlansFound: 'Nessun piano trovato',
    noUsersFound: 'Nessun utente trovato',
    // Friends
    requests: 'Richieste',
    noFriendsYet: 'Ancora nessun amico',
    noPendingRequests: 'Nessuna richiesta in attesa',
    wantsToBeYourFriend: 'Vuole essere tuo amico',
    noLocation: 'Nessuna posizione',
    // Notifications
    markAllRead: 'Segna tutte',
    removed: 'Rimosso',
    confirm: 'Conferma',
    delete: 'Elimina',
    friendRequest: ' ti ha mandato una richiesta di amicizia.',
    // MyStories
    noStoriesYet: 'Non hai ancora condiviso nessuno story',
    addFirstStory: 'Aggiungi Il Tuo Primo Story',
    unknownPlan: 'Piano Sconosciuto',
    // Plan Details
    going: 'Ci vado',
    groupChat: 'Chat di Gruppo',
    joinPlan: 'Unisciti al Piano',
    leavePlan: 'Esci',
    about: 'Info',
    experienceStories: 'Momenti',
    shareYourExperience: 'Condividi un\'esperienza incredibile',
    storiesUnavailableVoting: 'Stories non disponibili durante la votazione',
    planLimitWarning: 'Hai raggiunto il limite di 3 piani a',
    leaveToJoin: 'Lascia un piano per unirti a questo.',
    votingActiveNotice: '🗳️ Periodo di votazione attivo — Non puoi unirti o uscire durante la votazione (6 ore)',
    planTerminated: '❌ Piano Terminato',
    planTerminatedDesc: 'Questo piano è stato terminato dall\'admin e verrà eliminato in 24 ore',
    highlightPlan: 'Metti in evidenza questo piano - €2.99',
    // Story visibility
    friendsVisibility: 'Amici',
    groupOnly: 'Gruppo',
    // Welcome page
    welcomeHero: 'Ciao!',
    welcomeSubtitle: 'Unisciti a noi: ti aiutiamo a trovare e creare i migliori piani nella tua città!!!',
    downloadNow: 'Scarica Ora!',
    allRightsReserved: 'Tutti i diritti riservati.',
    // Group Chat
    votingOpen: 'Votazione aperta! Tocca per votare',
    awaitingAdminDecision: '⏳ In attesa che l\'admin rinnovi o chiuda il piano',
    renewPlan: 'Rinnova',
    terminatePlan: 'Chiudi',
    beFirstToMessage: 'Inizia la conv! Non essere timido',
    chatLocked: 'Chat bloccata — in attesa della decisione dell\'admin',
    messagePlaceholder: 'Messaggio...',
    // Admin actions
    adminActions: 'Azioni Admin',
    editPlan: 'Modifica Piano',
    editPlanUnavailableVoting: 'Non disponibile durante la votazione',
    editPlanUnavailableEnded: 'Non disponibile mentre il piano è chiuso',
    // Voting modal
    howWasPlan: 'Com\'era il piano?',
    yourOpinionHelps: 'La tua opinione aiuta a migliorare i futuri eventi',
    votingClosesIn: 'La votazione chiude 6 ore dopo la fine del piano',
    wantToLeavePlan: 'Vuoi lasciare questo piano?',
    youVotedBad: 'Hai votato che il piano non ti è piaciuto',
    yesLeavePlan: 'Sì, lascia il piano',
    noStayInGroup: 'No, rimango nel gruppo',
    // Renew plan modal
    adminActionsTitle: 'Azioni dell\'Admin',
    chooseWhatToDo: 'Scegli cosa fare con questo piano',
    renewPlanBtn: '🔄 Rinnova Piano',
    terminatePlanBtn: '❌ Termina Piano',
    cancel: 'Annulla',
    terminatePlanTitle: 'Termina Piano ❌',
    terminatePlanDesc: 'Il piano sarà contrassegnato come terminato e resterà visibile 24 ore prima di essere eliminato automaticamente.',
    terminateWarning: '⚠️ Non si può annullare. Tutti i membri vedranno che il piano è stato terminato.',
    back: 'Indietro',
    confirmTermination: 'Conferma Fine',
    renewPlanTitle: 'Rinnova Piano 🔄',
    renewPlanDesc: 'Tutto verrà rinnovato con nuova data e orario. I stories precedenti saranno mantenuti.',
    newDate: 'Nuova Data',
    startTime: 'Orario di Inizio',
    endTime: 'Orario di Fine',
    newAddress: 'Nuovo Indirizzo',
    fullAddress: 'Indirizzo completo',
    confirmRenewal: 'Conferma Rinnovo',
    // Delete plan modal
    terminatePlanQuestion: 'Chiudere il Piano?',
    terminatePlanVisibleDesc: 'Il piano sarà contrassegnato come Chiuso e visibile a tutti i membri per 24 ore, poi rimosso automaticamente.',
    terminatePlanConfirm: 'Chiudi Piano',
    // Plan renewed chat message
    planRenewed: "🔄 Il piano è stato rinnovato! Let's gooo 😎",
    planTerminatedMsg: '❌ L\'admin ha chiuso questo piano. Il gruppo verrà rimosso in 24 ore.',
    // Settings - Appearance & Privacy
    appearance: 'Aspetto',
    switchToLight: 'Passa al tema chiaro',
    switchToDark: 'Passa al tema scuro',
    darkMode: 'Modalità Scura',
    lightMode: 'Modalità Chiara',
    privateProfile: 'Profilo Privato',
    publicProfile: 'Profilo Pubblico',
    privateProfileDesc: 'Solo i tuoi amici vedono i tuoi stories, piani e amici',
    publicProfileDesc: 'Tutti possono vedere il tuo profilo completo',
    // GroupChat
    joinPlanToAccess: 'Unisciti al piano per accedere al gruppo e chattare.',
    backBtn: '← Indietro',
    planUpdated: '✏️ Piano aggiornato',
    terminatedBanner: '❌ Terminato',
    live: '🔵 In Diretta',
    add: 'Aggiungi',
    you: 'Tu',
    user: 'Utente',
    members: 'Membri',
    viewGroup: 'Visualizza Gruppo →',
    pinned: '📌 Fissato',
    notPinned: 'Non Fissato',
    noStoriesToPin: 'Nessuna Story da Fissare',
    noMessagesToPin: 'Nessun Messaggio da Fissare',
    inviteFriends: 'Invita Amici',
    noFriendsToInvite: 'Nessun Amico da Invitare',
    sent: 'Inviato',
    invite: 'Invita',
    admin: 'Amministratore',
    gallery: '📸 Galleria',
    noSharedMemories: 'Nessun Ricordo Condiviso Ancora',
    downloading: 'Scaricamento...',
    download: 'Scarica',
    noStickersYet: "Nessuno sticker ancora. Aggiungi il tuo primo!",
    searchAddress: 'Cerca indirizzo...',
    setCity: 'Imposta città',
    kmradius: 'raggio km',
    chooseCityDescription: 'Scegli una città per vedere piani vicino a te',
    chooseYourCity: 'o scegli la tua città',
    searchCity: '🔍 Cerca città...',
    select: 'Selezionare...',
    member: 'Membro',
    aboutCommunity: 'Informazioni su questa Comunità',
    active: 'Attivo',
    adminsCreatePlans: 'Gli admin creano piani',
    plansApproval: 'I piani richiedono approvazione',
    anyoneCreatePlans: 'Chiunque può creare piani',
    someone: 'Qualcuno',
    joinedAsAdmin: 'è entrato come Admin',
    joinedCommunity: 'è entrato nella comunità',
    newPlan: 'Nuovo piano',
    planCreated: 'piano creato',
    postedStory: 'ha pubblicato uno story',
    communityStats: 'Statistiche della Comunità',
    newMembersWeek: 'Nuovi Membri\nquesta settimana',
    storiesWeek: 'Stories\nquesta settimana',
    upcomingPlans: 'Piani\nin Arrivo',
    totalMembers: 'Totale Membri',
    joinedLast30d: 'Entrato negli ultimi 30g',
    liveActivity: 'Attività in Diretta',
    noActivityYet: 'Nessuna attività ancora',
    noActivityDesc: 'L\'attività apparirà qui man mano che i membri si uniscono e partecipano',
    challengeNight: '🌙 Sfida Notturna',
    challengeDay: '☀️ Sfida Diurna',
    challengeWeekend: '🎉 Sfida Weekend',
    challengeCustom: '⚡ Sfida',
    challengeTimeLeft: 'rimanenti',
    challengeEnded: 'Sfida terminata',
    challengeTapToParticipate: '📸 Tocca per vedere e partecipare →',
    storiesSubmitted: 'stories inviati',
    challengeWinner: 'Vincitore',
    challengePostToParticipate: '📸 Pubblica il tuo Story per partecipare',
    challengeFinalLeaderboard: '🏅 Classifica Finale',
    challengeLiveLeaderboard: '📊 Classifica in Diretta',
    storySingular: 'story',
    storiesPlural: 'stories',
    views: 'visualizzazioni',
    challengePickWinner: 'Scegli il Vincitore',
    challengeBeFirst: 'Sii il primo a partecipare!',
    createChallenge: 'Crea Sfida',
    createChallengeSubtitle: 'Annuncia una sfida di stories alla comunità',
    challengePickEmoji: 'Scegli un emoji',
    challengeType: 'Tipo',
    challengeTypeNight: 'Notte',
    challengeTypeNightDesc: 'Miglior story della serata',
    challengeTypeDay: 'Giorno',
    challengeTypeDayDesc: 'Miglior story del giorno',
    challengeTypeWeekend: 'Weekend',
    challengeTypeWeekendDesc: 'Vibe da weekend',
    challengeTypeCustom: 'Personalizzato',
    challengeTypeCustomDesc: 'Il tuo tema',
    challengeTitle: 'Titolo',
    challengeTitlePlaceholder: 'es: Miglior foto del tramonto stasera 🌅',
    challengeDescription: 'Descrizione',
    challengeDescriptionPlaceholder: 'Spiega ai membri che tipo di stories vuoi vedere...',
    challengeDuration: 'Durata',
    challengeDurationWeek: '1 settimana',
    challengePrize: 'Premio / Ricompensa',
    challengePrizePlaceholder: 'es: In evidenza sulla pagina della comunità 🏆',
    challengeLinkPlan: 'Collega a un Piano',
    challengeNoSpecificPlan: 'Nessun piano specifico',
    challengeLaunch: 'Lancia la Sfida',
    challengeNewNotifTitle: 'Nuova Sfida',
    challengeNewNotifMessage: 'È stata lanciata una nuova sfida! Pubblica il tuo story per partecipare.',
    optional: 'opzionale',
    editCommunity: 'Modifica Comunità',
    communityName: 'Nome',
    communityThemeColor: 'Colore del Tema',
    communityCoverImage: 'Foto di Copertina',
    communityChangePhoto: 'Cambia foto',
    communityCoverPhoto: 'Foto di copertina',
    communityBackgroundImage: 'Immagine di Sfondo',
    communityBackgroundTexture: 'Texture di sfondo',
    communityVisibility: 'Visibilità',
    communityPrivateDesc: 'Privata — nascosta da Home ed Esplora',
    communityPublicDesc: 'Pubblica — visibile a tutti',
    communityChatAccess: 'Accesso alla Chat',
    communityOpenToAll: 'Aperto a tutti',
    communityPlanPolicy: 'Politica di Creazione Piani',
    policyAnyone: 'Chiunque',
    policyApproval: 'Richiede Approvazione',
    policyAdminsOnly: 'Solo Admin',
    deleteCommunity: 'Elimina Comunità',
    leave: 'Esci',
    reportCommunity: 'Segnala Comunità',
    join: 'Unisciti 🚀',
    membersCount: 'membri',
    topMembers: 'Top Membri',
    total: 'totale',
    guideStep1Title: 'Benvenuto nella Comunità!',
    guideStep1Desc: 'Ora fai parte di questa comunità. Ecco una guida rapida per iniziare.',
    guideStep2Title: 'Unisciti e Crea Piani',
    guideStep2Desc: 'Esplora i piani nel tab Piani. Unisciti agli eventi o crea il tuo!',
    guideStep3Title: 'Condividi Stories',
    guideStep3Desc: 'Dopo un piano, posta stories per condividere la vibe con la comunità.',
    guideStep4Title: 'Conosci i Membri',
    guideStep4Desc: 'Vai nel tab Membri per vedere chi è attivo e scoprire i top contributor.',
    guideNext: 'Avanti',
    guideLetsGo: 'Andiamo! 🚀',
    guideBack: 'Indietro',
    eventStories: 'Stories dell\'Evento',
    moreStories: 'altre stories',
    leaveCommunityTitle: 'Lasciare la Comunità?',
    leaveCommunityConfirm: 'Sei sicuro di voler lasciare',
    sortBy: 'Ordina per',
    startTime: 'Ora di inizio',
    radius: 'Raggio',
    partyType: 'Tipo di festa',
    search: 'Cerca...',
    clearFilters: 'Cancella filtri',
    showMe: 'Mostrami',
    ageRange: 'Fascia d’età',
    city: 'Città',
    searchCityPlaceholder: 'Cerca per città...',
    vybtPlusCity: 'Esplora utenti di qualsiasi città con Vybt Plus',
    similarVibes: 'Vibes simili',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  React.useEffect(() => {
    const handler = () => {
      const lang = localStorage.getItem('app_language') || 'en';
      setLanguage(lang);
    };
    window.addEventListener('languagechange', handler);
    return () => window.removeEventListener('languagechange', handler);
  }, []);

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}